const modelData = [
  {
    "category": "Tile-Level Vision Foundation Models",
    "models": [
      {
        "name": "CTransPath",
        "year": 2022,
        "data": "32K+ WSIs",
        "idea": "SRCL with hybrid CNN-ViT",
        "github": "https://github.com/Xiyue-Wang/TransPath",
        "hf": "",
        "paper": "https://www.sciencedirect.com/science/article/pii/S1361841522002043",
        "audit_wsis": ">30,000",
        "audit_patches": "~15M patches",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": ">25 anatomic sites; 32 cancer subtypes",
        "audit_downstream": "5 task families: patch retrieval, supervised patch classification, weakly supervised WSI classification, mitosis detection, colorectal gland segmentation; 9 public datasets",
        "audit_cohorts": "Pretraining sources TCGA + PAIP; exact institution count Not found",
        "audit_notes": "Public-source pathology corpus; SRCL hybrid CNN\u2013ViT.",
        "paper_title": "TransPath: Transformer-Based Self-supervised Learning for Histopathological Image Classification",
        "paper_author": "Wang"
      },
      {
        "name": "REMEDIS",
        "year": 2023,
        "data": "29K+ WSIs",
        "idea": "BiT + SimCLR Pretraining",
        "github": "",
        "hf": "",
        "paper": "https://doi.org/10.1038/s41551-023-01049-7",
        "audit_wsis": "29,018",
        "audit_patches": "50M pathology images",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "Not found as a single pathology-specific total",
        "audit_cohorts": "TCGA for pathology SSL; exact institution count Not found",
        "audit_notes": "The 29,018/50M figures are explicitly restated in the Prov-GigaPath methods comparison; REMEDIS also covers non-pathology medical imaging.",
        "paper_title": "Robust and data-efficient generalization of self-supervised machine learning for diagnostic imaging",
        "paper_author": "Azizi"
      },
      {
        "name": "Lunit",
        "year": 2023,
        "data": "36K+ WSI",
        "idea": "Pathology-Specific SSL Pretraining",
        "github": "https://github.com/lunit-io/benchmark-ssl-pathology",
        "hf": "https://huggingface.co/1aurent/vit_small_patch8_224.lunit_dino",
        "paper": "https://arxiv.org/abs/2212.04690",
        "audit_wsis": "36,666",
        "audit_patches": "32,578,557 patches",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Multiple cancers; exact organ count Not found",
        "audit_downstream": "2 task types over 5 datasets: classification on BACH, CRC, MHIST, PatchCamelyon; nuclei instance segmentation/classification on CoNSeP",
        "audit_cohorts": "2 pretraining sources: TCGA 20,994 WSIs + internal TULIP 15,672",
        "audit_notes": "19,000,069 TCGA + 13,578,488 TULIP patches; 20\u00d7/40\u00d7.",
        "paper_title": "Benchmarking Self-Supervised Learning on Diverse Pathology Datasets",
        "paper_author": "Kang"
      },
      {
        "name": "Phikon",
        "year": 2023,
        "data": "6,093 WSIs",
        "idea": "iBOT Masked Image Pretraining",
        "github": "https://github.com/owkin/HistoSSLscaling/",
        "hf": "https://huggingface.co/owkin/phikon",
        "paper": "https://www.medrxiv.org/content/10.1101/2023.07.21.23292757v2",
        "audit_wsis": "6,093 TCGA WSIs",
        "audit_patches": ">40M pan-cancer tiles",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "16 cancer types",
        "audit_downstream": "Exact scalar task count Not found; patch- and WSI-level cancer tasks",
        "audit_cohorts": "TCGA public source",
        "audit_notes": "iBOT pretraining; official Owkin material reports >40M images. The 6,093-slide PanCancer corpus is independently specified by the H0-mini official material.",
        "paper_title": "load an image",
        "paper_author": "Filiot"
      },
      {
        "name": "PathoDuet",
        "year": 2024,
        "data": "11K WSIs",
        "idea": "Cross-Scale Cross-Stain Pretraining",
        "github": "https://github.com/openmedlab/PathoDuet",
        "hf": "",
        "paper": "https://www.sciencedirect.com/science/article/pii/S1361841524002147",
        "audit_wsis": "~11,000",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Paired H&E\u2013IHC used; exact pair count Not found",
        "audit_organs": "Pan-cancer; exact tissue count Not found",
        "audit_downstream": "Patch classification, WSI classification, PD-L1 expression classification, cross-site IHC tumor identification",
        "audit_cohorts": "TCGA, HyReCo, BCI and downstream public datasets; institution count Not found",
        "audit_notes": "Cross-scale/cross-stain learning; exact unique pretraining patch total not recovered.",
        "paper_title": "PathoDuet: Foundation Models for Pathological Slide Analysis of H&E and IHC Stains",
        "paper_author": "Hua"
      },
      {
        "name": "RudolfV",
        "year": 2024,
        "data": "134K WSIs, 58 tissue types",
        "idea": "Pathologist-curated data and expertise",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2401.04079",
        "audit_wsis": "**Not found**",
        "audit_patches": "**Not found**",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "58 tissue types; 129 histochemical/IHC stain modalities",
        "audit_downstream": "Tumor-microenvironment profiling, biomarker evaluation, reference-case search; exact task count Not found",
        "audit_cohorts": ">15 laboratories across Europe/US",
        "audit_notes": "The often-repeated seed-list slide total was not visible in the primary text I could verify, so it is deliberately not reproduced.",
        "paper_title": "RudolfV: A Foundation Model by Pathologists for Pathologists",
        "paper_author": "Dippel"
      },
      {
        "name": "PLUTO",
        "year": 2024,
        "data": "195M tiles",
        "idea": "Lightweight multi-scale representation",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2405.07905",
        "audit_wsis": "**Not found**",
        "audit_patches": "195M image tiles",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "3 broad scales: instance segmentation, tile classification, slide-level prediction",
        "audit_cohorts": "Multiple sites; exact count Not found",
        "audit_notes": "Multi-scale pathology representation learning.",
        "paper_title": "PLUTO: Pathology-Universal Transformer",
        "paper_author": "Juyal"
      },
      {
        "name": "UNI",
        "year": 2024,
        "data": "100M tiles, 100K WSIs",
        "idea": "General-purpose DINOv2 on 100K WSIs",
        "github": "https://github.com/mahmoodlab/UNI",
        "hf": "",
        "paper": "https://doi.org/10.1038/s41591-024-02857-3",
        "audit_wsis": ">100K WSIs",
        "audit_patches": ">100M images",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "20 major tissue types",
        "audit_downstream": "34 representative CPath tasks",
        "audit_cohorts": "Two hospitals plus GTEx are reported as principal sources",
        "audit_notes": ">77 TB diagnostic H&E; public/private mix.",
        "paper_title": "Towards a general-purpose foundation model for computational pathology",
        "paper_author": "Chen"
      },
      {
        "name": "Virchow",
        "year": 2024,
        "data": "1.5M WSIs, 100K patients",
        "idea": "Clinical-grade pan-cancer detection",
        "github": "",
        "hf": "https://huggingface.co/paige-ai/Virchow",
        "paper": "https://doi.org/10.1038/s41591-024-03141-0",
        "audit_wsis": "~1.5M H&E WSIs",
        "audit_patches": "~2B sampled training tiles; ~13B available tissue tiles",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "17 high-level tissue groups",
        "audit_downstream": "Pan-cancer detection across 17 types, rare-cancer detection across 7 rare types, tile benchmarks and slide biomarker prediction; one aggregate task count Not found",
        "audit_cohorts": "Pretraining at MSKCC; external evaluation includes 7 additional clinical datasets",
        "audit_notes": "~100K patients; **2B is sampled training instances, not unique patches**.",
        "paper_title": "A foundation model for clinical-grade computational pathology and rare cancers detection",
        "paper_author": "Vorontsov"
      },
      {
        "name": "Virchow2",
        "year": 2024,
        "data": "3.1M WSIs",
        "idea": "1.9B parameters, mixed magnification",
        "github": "",
        "hf": "https://huggingface.co/paige-ai/Virchow2",
        "paper": "https://arxiv.org/abs/2408.00738",
        "audit_wsis": "3.1M",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Nearly 200 tissue types",
        "audit_downstream": "12 tile-level downstream tasks reported",
        "audit_cohorts": "225,401 patients; exact institution count Not found",
        "audit_notes": "Mixed 5\u00d7/10\u00d7/20\u00d7/40\u00d7; H&E + IHC diversity.",
        "paper_title": "Virchow2: Scaling Self-Supervised Mixed Magnification Models in Pathology",
        "paper_author": "Zimmermann"
      },
      {
        "name": "Hibou",
        "year": 2024,
        "data": "1M WSIs",
        "idea": "Open-source DINOv2 architecture",
        "github": "https://github.com/histai/hibou",
        "hf": "https://huggingface.co/histai/hibou-L",
        "paper": "https://arxiv.org/abs/2406.05074",
        "audit_wsis": ">1M",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Diverse tissues; exact count Not found",
        "audit_downstream": "Patch- and slide-level benchmarks; exact task count Not found",
        "audit_cohorts": "Proprietary corpus; institution count Not found",
        "audit_notes": "I retained only the >1M number explicitly visible in the primary description.",
        "paper_title": "Hibou: A Family of Foundational Vision Transformers for Pathology",
        "paper_author": "Nechaev"
      },
      {
        "name": "BEPH",
        "year": 2024,
        "data": "11M tiles",
        "idea": "BEiT-based masked image modeling",
        "github": "https://github.com/Zhcyoung/BEPH",
        "hf": "",
        "paper": "https://www.nature.com/articles/s41467-025-57587-y",
        "audit_wsis": "**Not found**",
        "audit_patches": "~11M unlabeled pathology images",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "3 task families: patch cancer diagnosis, WSI cancer classification, survival prediction",
        "audit_cohorts": "Not found",
        "audit_notes": "BEiT-style masked-image pretraining.",
        "paper_title": "A foundation model for generalizable cancer diagnosis and survival prediction from histopathological images",
        "paper_author": "Yang"
      },
      {
        "name": "Atlas",
        "year": 2025,
        "data": "1.2M WSIs (Mayo + Charit\u00e9)",
        "idea": "Efficient RudolfV-based model",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2501.05409",
        "audit_wsis": "1.2M",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "21 public benchmark datasets",
        "audit_cohorts": "2 institutions: Mayo Clinic + Charit\u00e9",
        "audit_notes": "Large private multi-institution clinical corpus.",
        "paper_title": "Atlas: A Novel Pathology Foundation Model by Mayo Clinic, Charit\\'e, and Aignostics",
        "paper_author": "Alber"
      },
      {
        "name": "Midnight",
        "year": 2025,
        "data": "12K / 92K WSIs",
        "idea": "Data-efficient DINOv2 optimization",
        "github": "https://github.com/kaiko-ai/midnight",
        "hf": "",
        "paper": "https://arxiv.org/abs/2504.05186",
        "audit_wsis": "12K / 92K",
        "audit_patches": "384M sampled tile instances over training; not a fixed unique corpus",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "TCGA: 32 cancer types; NKI extension: 31 organs",
        "audit_downstream": "BACH, BRACS, BreaKHis, CRC100K, Gleason TMA, MHIST, PatchCamelyon, Camelyon16, PANDA, CoNSeP, MoNuSAC, HEST; HEST contains 9 ST gene-expression tasks",
        "audit_cohorts": "TCGA + NKI; NKI includes 10,141 patients",
        "audit_notes": "Midnight-12k is public TCGA; Midnight-92k adds 80K proprietary NKI slides; online tile extraction.",
        "paper_title": "Training state-of-the-art pathology foundation models with orders of magnitude less data",
        "paper_author": "Karasikov"
      },
      {
        "name": "H-optimus-0",
        "year": 2025,
        "data": "500K WSIs",
        "idea": "SSL Pretraining, FM Distillation",
        "github": "https://github.com/bioptimus/releases/tree/main/models/h-optimus/v0",
        "hf": "https://huggingface.co/bioptimus/H-optimus-0",
        "paper": "https://arxiv.org/abs/2501.16239v1",
        "audit_wsis": ">500K proprietary H&E WSIs",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "Examples include mutation prediction, survival prediction, tissue classification; exact count Not found",
        "audit_cohorts": "Not found",
        "audit_notes": "1.1B-parameter tile FM; private corpus.",
        "paper_title": "Distilling foundation models for robust and efficient models in digital pathology",
        "paper_author": "Filiot"
      },
      {
        "name": "PathOrchestra",
        "year": 2025,
        "data": "27K WSIs, 100 tasks",
        "idea": "Evaluated on 112 clinical tasks",
        "github": "",
        "hf": "https://huggingface.co/AI4Pathology/PathOrchestra",
        "paper": "https://arxiv.org/abs/2503.24345",
        "audit_wsis": "**287,424 H&E WSIs**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "21 tissues/organs/systems",
        "audit_downstream": "**112 tasks: 61 WSI + 51 ROI**; slide preprocessing 12, pan-cancer 3, lesion identification 15, cancer subtyping 36, biomarker evaluation 36, gene-expression assessment 10",
        "audit_cohorts": "**3 pretraining centers**; evaluation uses 51 public + 61 private datasets",
        "audit_notes": "Evaluation corpus is 27,755 WSIs + 9,415,729 ROIs; >35 stains and >50 genes.",
        "paper_title": "PathOrchestra: A Comprehensive Foundation Model for Computational Pathology with Over 100 Diverse Clinical-Grade Tasks",
        "paper_author": "Yan"
      },
      {
        "name": "GenBio-PathFM",
        "year": 2026,
        "data": "177K WSIs",
        "idea": "JEDI (JEPA+DINO) dual-stage learning",
        "github": "https://github.com/genbio-ai/genbio-pathfm",
        "hf": "",
        "paper": "https://www.biorxiv.org/content/10.64898/2026.03.17.712534v1",
        "audit_wsis": "**Not found**",
        "audit_patches": "**Not found**",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "THUNDER, HEST, PathoROB benchmark families; exact total Not found",
        "audit_cohorts": "Public-only training; number of source cohorts/institutions Not found",
        "audit_notes": "Official materials confirm JEDI (JEPA + DINO) and public-only data, but exact requested scale statistics remained unresolved.",
        "paper_title": "GenBio-PathFM: A State-of-the-Art Foundation Model for Histopathology",
        "paper_author": "Kapse"
      },
      {
        "name": "RudolfV2",
        "year": 2026,
        "data": "300K+ WSIs",
        "idea": "Robust Multi-Scale SSL Pretraining",
        "github": "",
        "hf": "https://huggingface.co/Aignostics/RudolfV-2",
        "paper": "https://cdn.prod.website-files.com/67adb01f31489469b513304a/6a74e2f9f1d4aef06489a3f1_RudolfV_2_260806.pdf",
        "audit_wsis": "**Not found**",
        "audit_patches": "**Not found**",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "**Not found**",
        "audit_downstream": "**Not found**",
        "audit_cohorts": "**Not found**",
        "audit_notes": "Official paper/model links were identified, but I did not recover the requested exact metadata from primary text in a form I could verify; seed-list values are therefore not treated as confirmed.",
        "paper_title": "RudolfV 2: A Family of Robust and Efficient Open-Weights Pathology Foundation Models",
        "paper_author": "Milbich"
      },
      {
        "name": "Atlas 2",
        "year": 2026,
        "data": "5.5M WSIs",
        "idea": "2B params, robust evaluation on 80 benchmarks",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/pdf/2601.05148",
        "audit_wsis": "**5.5M WSIs**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "70+ tissue types; 100+ staining types",
        "audit_downstream": "**80 public benchmarks**",
        "audit_cohorts": "3 institutions: Charit\u00e9, LMU Munich, Mayo Clinic",
        "audit_notes": "~490K cases and 7 scanner types reported by official project material.",
        "paper_title": "Atlas 2 -- Foundation models for clinical deployment",
        "paper_author": "Alber"
      },
      {
        "name": "GRACE",
        "year": 2026,
        "data": "48K WSIs",
        "idea": "Gastric-specific foundation model",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2606.04792",
        "audit_wsis": "**Not found** as isolated pretraining subset; 48,364 total development/validation WSIs",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Stomach/gastric, 1 organ focus",
        "audit_downstream": "**28 clinically relevant tasks** spanning precancerous lesions, histopathologic assessment, molecular profiling and prognosis",
        "audit_cohorts": "Multicenter; exact institution number Not found; 37,493 patients",
        "audit_notes": "48,364 total WSIs must not automatically be labeled \u201cpretraining WSIs.\u201d",
        "paper_title": "A Pathology Foundation Model for Gastric Cancer with Real-World Validation",
        "paper_author": "Liang"
      }
    ]
  },
  {
    "category": "Slide-Level & Patient-Level Foundation Models",
    "models": [
      {
        "name": "Prov-GigaPath",
        "year": 2024,
        "data": "1.3B tiles, 171K WSIs",
        "idea": "LongNet for ultra-large context",
        "github": "https://github.com/prov-gigapath/prov-gigapath",
        "hf": "https://huggingface.co/prov-gigapath/prov-gigapath",
        "paper": "https://www.nature.com/articles/s41586-024-07441-w",
        "audit_wsis": "**171,189 H&E/IHC WSIs**",
        "audit_patches": "**1,384,860,229 256\u00d7256 tiles**",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Reports used in V-L experiment, but **exact WSI\u2013report pair count Not found**",
        "audit_image_omics": "Not found",
        "audit_organs": "31 major tissue types",
        "audit_downstream": "**26 tasks: 9 cancer-subtyping + 17 pathomics**",
        "audit_cohorts": "Providence network: **28 cancer centers**, >30K patients",
        "audit_notes": "Private real-world clinical corpus; DINOv2 tile encoder + LongNet/MAE slide encoder.",
        "paper_title": "A whole-slide foundation model for digital pathology from real-world data",
        "paper_author": "Xu"
      },
      {
        "name": "CHIEF",
        "year": 2024,
        "data": "60K WSIs, 19 sites",
        "idea": "Weakly supervised slide pattern recognition",
        "github": "https://github.com/hms-dbmi/CHIEF",
        "hf": "",
        "paper": "https://www.nature.com/articles/s41586-024-07894-z",
        "audit_wsis": "**60,530 WSIs**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "**19 anatomical sites**",
        "audit_downstream": "Cancer detection, tumor-origin identification, molecular-profile prediction and prognosis; exact scalar count Not found",
        "audit_cohorts": "Validation: **32 independent slide sets from 24 hospitals/cohorts**",
        "audit_notes": "44-TB pretraining corpus; external validation includes 19,491 WSIs.",
        "paper_title": "A pathology foundation model for cancer diagnosis and prognosis prediction",
        "paper_author": "Wang"
      },
      {
        "name": "Feather",
        "year": 2025,
        "data": "3,499 WSIs",
        "idea": "Transferable Pretrained MIL Models",
        "github": "https://github.com/mahmoodlab/MIL-Lab",
        "hf": "https://huggingface.co/collections/MahmoodLab/feather",
        "paper": "https://arxiv.org/abs/2506.09022",
        "audit_wsis": "**Not found**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "**Not found**",
        "audit_cohorts": "**Not found**",
        "audit_notes": "Primary paper identified; the exact requested scale/evaluation totals were not recovered after the second pass, so the seed 3,499-WSI value is not promoted here.",
        "paper_title": "Do Multiple Instance Learning Models Transfer?",
        "paper_author": "Shao"
      },
      {
        "name": "EXAONE Path 2.0",
        "year": 2025,
        "data": "37K WSIs",
        "idea": "End-to-end hierarchical learning",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/pdf/2507.06639",
        "audit_wsis": "**37K WSIs**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "**10 biomarker-prediction tasks**",
        "audit_cohorts": "Not found",
        "audit_notes": "End-to-end hierarchical/direct slide-level supervision.",
        "paper_title": "EXAONE Path 2.0: Pathology Foundation Model with End-to-End Supervision",
        "paper_author": "Pyeon"
      },
      {
        "name": "MOOZY",
        "year": 2026,
        "data": "77K WSIs",
        "idea": "Patient-first case-level aggregator",
        "github": "https://github.com/AtlasAnalyticsLab/MOOZY",
        "hf": "",
        "paper": "https://arxiv.org/abs/2603.27048",
        "audit_wsis": "**77,134 public slides**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "**23 anatomical sites**",
        "audit_downstream": "**333 tasks: 205 classification + 128 survival**",
        "audit_cohorts": "**56 public datasets**; exact institution count Not found",
        "audit_notes": "Entirely public; patient-first case-level transformer models inter-slide relationships.",
        "paper_title": "MOOZY: A Patient-First Foundation Model for Computational Pathology",
        "paper_author": "Kotp"
      },
      {
        "name": "GigaPath-Flash",
        "year": 2026,
        "data": "Real-world Providence cohort",
        "idea": "Efficient 43M ViT-S+LongNet whole-slide foundation model",
        "github": "",
        "hf": "https://huggingface.co/prov-gigapath/prov-gigapath-flash",
        "paper": "https://arxiv.org/abs/2607.18218",
        "audit_wsis": "**Not found**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "Slide-level pathology evaluation; exact task count Not found",
        "audit_cohorts": "Large real-world clinical data; exact centers Not found in accessible primary description",
        "audit_notes": "22M ViT-S + 21M LongNet; tile encoder distilled from GigaPath; open-weight Apache-2.0.",
        "paper_title": "GigaPath-Flash and GigaTIME-Flash: Efficient Pathology Foundation Models for Whole-Slide and Tumor Microenvironment Analysis",
        "paper_author": "Usuyama"
      }
    ]
  },
  {
    "category": "Vision-Language Foundation Models",
    "models": [
      {
        "name": "PLIP",
        "year": 2023,
        "data": "208K image-text pairs",
        "idea": "Pretrained on medical Twitter",
        "github": "https://github.com/pathologyfoundation/plip",
        "hf": "https://huggingface.co/vinid/plip",
        "paper": "https://doi.org/10.1038/s41591-023-02504-3",
        "audit_wsis": "Not found",
        "audit_patches": "208,414 pathology images",
        "audit_image_text": "**208,414 image\u2013text pairs**",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "4 external zero-shot classification datasets + image/text retrieval",
        "audit_cohorts": "OpenPath / medical Twitter + LAION; institution count not applicable/reported",
        "audit_notes": "Crowdsourced public image-description data.",
        "paper_title": "A visual\u2013language foundation model for pathology image analysis using medical Twitter",
        "paper_author": "Huang"
      },
      {
        "name": "CONCH",
        "year": 2024,
        "data": "1.17M image-text pairs",
        "idea": "CoCa-based task-agnostic pretraining",
        "github": "https://github.com/mahmoodlab/CONCH",
        "hf": "https://huggingface.co/MahmoodLab/CONCH",
        "paper": "https://doi.org/10.1038/s41591-024-02856-4",
        "audit_wsis": "Not found",
        "audit_patches": "Not found",
        "audit_image_text": "**>1.17M image\u2013caption pairs**",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Diverse histopathology; exact count Not found",
        "audit_downstream": "**14 benchmarks** spanning classification, segmentation, captioning, text\u2192image and image\u2192text retrieval, including slide-level few-shot evaluation",
        "audit_cohorts": "Multiple sources; exact institution count Not found",
        "audit_notes": "CoCa-style task-agnostic pathology VLM.",
        "paper_title": "A visual-language foundation model for computational pathology",
        "paper_author": "Lu"
      },
      {
        "name": "PRISM",
        "year": 2024,
        "data": "Virchow tiles + reports",
        "idea": "Generative model via Virchow tiles",
        "github": "",
        "hf": "https://huggingface.co/paige-ai/Prism",
        "paper": "https://arxiv.org/abs/2405.10254",
        "audit_wsis": "**587K WSIs**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "**Not found**; 195K clinical reports, but no explicit one-to-one WSI-report count",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "Report generation, zero-shot cancer detection/subtyping, biomarker identification, slide classification; exact total Not found",
        "audit_cohorts": "**MSKCC**",
        "audit_notes": "Virchow tile embeddings + reports. Do not relabel \u201c195K reports\u201d as \u201c195K WSI-report pairs.\u201d",
        "paper_title": "PRISM: A Multi-Modal Generative Foundation Model for Slide-Level Histopathology",
        "paper_author": "Shaikovski"
      },
      {
        "name": "MUSK",
        "year": 2025,
        "data": "50M images + 1B text tokens",
        "idea": "Unified masked modeling",
        "github": "https://github.com/lilab-stanford/MUSK",
        "hf": "",
        "paper": "https://www.nature.com/articles/s41586-024-08378-w",
        "audit_wsis": "Not found",
        "audit_patches": "**50M pathology images**",
        "audit_image_text": "**1M image\u2013text pairs** in alignment stage",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Exact organ count Not found",
        "audit_downstream": "**23 patch- and slide-level benchmarks**, including retrieval, VQA, classification and biomarker prediction",
        "audit_cohorts": "**11,577 patients**; institution count Not found",
        "audit_notes": "First-stage language corpus also contains **1B pathology-related text tokens**; initial image/text can be unpaired.",
        "paper_title": "A vision\u2013language foundation model for precision oncology",
        "paper_author": "Xiang"
      },
      {
        "name": "TITAN",
        "year": 2025,
        "data": "335K WSIs + reports",
        "idea": "Whole-slide alignment with reports",
        "github": "https://github.com/mahmoodlab/TITAN",
        "hf": "https://huggingface.co/MahmoodLab/TITAN",
        "paper": "https://www.nature.com/articles/s41591-025-03982-3",
        "audit_wsis": "**335,645 WSIs**",
        "audit_patches": "Not found",
        "audit_image_text": "**423,122 synthetic image/ROI\u2013caption examples**",
        "audit_wsi_report": "**Not found**; >182K pathology reports, exact slide-report cardinality unspecified",
        "audit_image_omics": "Not found",
        "audit_organs": "**20 organs**",
        "audit_downstream": "6 broad families: linear probing, few-shot classification, zero-shot classification, rare-cancer retrieval, cross-modal retrieval, report generation",
        "audit_cohorts": "Mass General Brigham; exact contributing-site count Not found",
        "audit_notes": "89.7% H&E, 7.9% IHC, 2.3% special stains, 0.1% other; captions generated with PathChat.",
        "paper_title": "A multimodal whole-slide foundation model for pathology",
        "paper_author": "Ding"
      },
      {
        "name": "CPath-Omni",
        "year": 2025,
        "data": "700k image-caption + WSI report",
        "idea": "Unified Patch\u2013Slide Multimodal Model",
        "github": "https://github.com/PathFoundation/CPath-Omni",
        "hf": "",
        "paper": "https://arxiv.org/pdf/2412.12077",
        "audit_wsis": "**Not found**",
        "audit_patches": "**Not found**",
        "audit_image_text": "**Not found**",
        "audit_wsi_report": "**Not found**",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "**7 task types across 42 datasets**; includes classification, VQA, captioning and visual referring prompting",
        "audit_cohorts": "Not found",
        "audit_notes": "15B unified patch/WSI multimodal model; the seed-list ~700K image-caption figure was not independently re-established, so it remains Not found.",
        "paper_title": "CPath-Omni: A Unified Multimodal Foundation Model for Patch and Whole Slide Image Analysis in Computational Pathology",
        "paper_author": "Sun"
      },
      {
        "name": "KEEP",
        "year": 2026,
        "data": "143K knowledge-grouped pairs",
        "idea": "Disease knowledge graph integration",
        "github": "https://github.com/MAGIC-AI4Med/KEEP",
        "hf": "https://huggingface.co/Astaxanthin/KEEP",
        "paper": "https://arxiv.org/abs/2412.13126",
        "audit_wsis": "**Not found**",
        "audit_patches": "**Not found**",
        "audit_image_text": "**Not found**",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "**Not found**",
        "audit_cohorts": "**Not found**",
        "audit_notes": "Knowledge-graph-enhanced pathology VLM; the seed 143K \u201cknowledge-grouped pairs\u201d number was not independently recovered to the standard used here.",
        "paper_title": "Knowledge-enhanced Pretraining for Vision-language Pathology Foundation Model on Cancer Diagnosis",
        "paper_author": "Zhou"
      },
      {
        "name": "PRISM2",
        "year": 2026,
        "data": "2.3M WSIs",
        "idea": "Clinical Dialogue Multimodal Pretraining",
        "github": "",
        "hf": "https://huggingface.co/paige-ai/Prism2",
        "paper": "https://arxiv.org/abs/2506.13063",
        "audit_wsis": "**2.3M WSIs**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "**Not found**; nearly 700K specimens / 2.3M WSIs are associated with real diagnostic reports, but no explicit pair total was isolated",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "Diagnostic/biomarker/report-QA and survival-oriented evaluations; exact total Not found",
        "audit_cohorts": "Nearly 700K specimens; institution count Not found",
        "audit_notes": "One report-bearing specimen can have several slides, hence 2.3M \u2260 2.3M WSI-report pairs.",
        "paper_title": "PRISM2: Unlocking Multi-Modal General Pathology AI with Clinical Dialogue",
        "paper_author": "Vorontsov"
      }
    ]
  },
  {
    "category": "Multimodal & Molecular Foundation Models",
    "models": [
      {
        "name": "Tangle",
        "year": 2024,
        "data": "8.6K paired (slide + RNA-seq)",
        "idea": "Transcriptomics-aligned slide representation",
        "github": "https://github.com/mahmoodlab/Tangle",
        "hf": "",
        "paper": "https://arxiv.org/abs/2405.11618",
        "audit_wsis": "**Not found**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "H&E \u2194 bulk RNA-seq alignment; **exact pair count Not found**",
        "audit_organs": "Not found",
        "audit_downstream": "Not found",
        "audit_cohorts": "Not found",
        "audit_notes": "The widely repeated ~8.6K paired number was not independently recovered in accessible primary text during this audit, so it is not asserted.",
        "paper_title": "Transcriptomics-guided Slide Representation Learning in Computational Pathology",
        "paper_author": "Jaume"
      },
      {
        "name": "Madeleine",
        "year": 2025,
        "data": "4,211 WSIs (Paired Multi-Stain)",
        "idea": "Multistain Cross-Stain Slide Pretraining",
        "github": "https://github.com/mahmoodlab/MADELEINE",
        "hf": "https://huggingface.co/MahmoodLab/madeleine",
        "paper": "https://arxiv.org/pdf/2408.02859",
        "audit_wsis": "**Not found**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Paired multi-stain histology; **exact pair count Not found**",
        "audit_organs": "Not found",
        "audit_downstream": "**Not found**",
        "audit_cohorts": "**Not found**",
        "audit_notes": "Cross-stain slide pretraining; the seed 4,211-WSI value was not independently recovered to the strict standard here.",
        "paper_title": "Multistain Pretraining for Slide Representation Learning in Pathology",
        "paper_author": "Jaume"
      },
      {
        "name": "Threads",
        "year": 2025,
        "data": "47K paired (H&E + multi-omics)",
        "idea": "Multi-omics driven representation",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/html/2501.16652v1",
        "audit_wsis": "Not relabeled as WSI count",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "**47,171 H&E tissue sections paired with genomic + transcriptomic profiles**",
        "audit_organs": "Not found",
        "audit_downstream": "**54 oncology tasks**, including clinical subtyping, grading, mutation, IHC status, treatment response and survival",
        "audit_cohorts": "Exact cohort/institution count Not found",
        "audit_notes": "Primary paper says **tissue sections**; I do not automatically rewrite that as 47,171 distinct WSIs.",
        "paper_title": "Molecular-driven Foundation Model for Oncologic Pathology",
        "paper_author": "Vaidya"
      },
      {
        "name": "mSTAR",
        "year": 2025,
        "data": "26K paired triplets",
        "idea": "Slide, report, and RNA-seq integration",
        "github": "https://github.com/Innse/mSTAR",
        "hf": "https://huggingface.co/Wangyh/mSTAR",
        "paper": "https://www.nature.com/articles/s41467-025-66220-x",
        "audit_wsis": "**Not found**",
        "audit_patches": "**>116M patch images**",
        "audit_image_text": "Not found",
        "audit_wsi_report": "**Not found** as a separate count",
        "audit_image_omics": "**26,169 aggregate slide-level modality pairs** spanning H&E WSIs, reports and RNA-seq; 10,275 patients",
        "audit_organs": "**32 cancer types**",
        "audit_downstream": "**43 subtasks across 7 task types**",
        "audit_cohorts": "Institution count Not found",
        "audit_notes": "Crucially, the 26,169 aggregate multimodal pairs cannot be safely split into invented WSI-report and WSI-RNA counts.",
        "paper_title": "A multimodal knowledge-enhanced whole-slide pathology foundation model",
        "paper_author": "Xu"
      },
      {
        "name": "KRONOS",
        "year": 2025,
        "data": "47M patches",
        "idea": "Foundation model built for spatial proteomics via segmentation-free patch-level processing",
        "github": "https://github.com/mahmoodlab/KRONOS",
        "hf": "https://huggingface.co/MahmoodLab/KRONOS",
        "paper": "https://arxiv.org/abs/2506.03373",
        "audit_wsis": "N/A \u2014 spatial-proteomics image corpus rather than conventional WSI pretraining",
        "audit_patches": "**>47M spatial-proteomics image patches**",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "47M+ patches cover **175 protein markers**; a separate \u201cimage\u2013omics pair\u201d total beyond the patch corpus is Not found",
        "audit_organs": "**16 tissue types**",
        "audit_downstream": "Cell phenotyping, region classification, patient stratification, treatment-response prediction, retrieval/reverse search; exact scalar count Not found",
        "audit_cohorts": "**11 independent evaluation cohorts; 8 fluorescence imaging platforms**",
        "audit_notes": "Segmentation-free, multi-channel spatial-proteomics FM.",
        "paper_title": "A Foundation Model for Spatial Proteomics",
        "paper_author": "Shaban"
      },
      {
        "name": "EXAONE Path 2.5",
        "year": 2025,
        "data": "37K WSIs",
        "idea": "End-to-end hierarchical learning with direct slide-level supervision",
        "github": "",
        "hf": "https://huggingface.co/LGAI-EXAONE/EXAONE-Path-2.5",
        "paper": "https://arxiv.org/abs/2512.14019",
        "audit_wsis": "**Not found**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Histology aligned with **genomic, epigenetic and transcriptomic** modalities; exact paired-example count Not found",
        "audit_organs": "Not found",
        "audit_downstream": "Patho-Bench **80 tasks** + internal real-world clinical benchmark; exact combined total Not found",
        "audit_cohorts": "Two evaluation settings; institution count Not found",
        "audit_notes": "All-pairwise SigLIP-style multimodal alignment; pretraining sample counts not explicit in accessible abstract.",
        "paper_title": "EXAONE Path 2.5: Pathology Foundation Model with Multi-Omics Alignment",
        "paper_author": "Yun"
      },
      {
        "name": "CARE",
        "year": 2026,
        "data": "34K WSIs",
        "idea": "Molecular-Guided Adaptive Region Modeling",
        "github": "https://github.com/zdipath/CARE",
        "hf": "https://huggingface.co/Zipper-1/CARE",
        "paper": "https://arxiv.org/abs/2602.21637",
        "audit_wsis": "**Not found**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Molecular-guided slide learning; **exact pair count/modality total Not found**",
        "audit_organs": "Not found",
        "audit_downstream": "**Not found**",
        "audit_cohorts": "**Not found**",
        "audit_notes": "The 34K-WSI seed value was not independently verified in the accessible primary material, so it remains Not found.",
        "paper_title": "CARE: A Molecular-Guided Foundation Model with Adaptive Region Modeling for Whole Slide Image Analysis",
        "paper_author": "Zhang"
      },
      {
        "name": "KRONOS2",
        "year": 2026,
        "data": "---",
        "idea": "---",
        "github": "",
        "hf": "https://huggingface.co/MahmoodLab/KRONOS2",
        "paper": "https://arxiv.org/abs/2506.03373",
        "audit_wsis": "**Not found**",
        "audit_patches": "**Not found**",
        "audit_image_text": "**Not found**",
        "audit_wsi_report": "**Not found**",
        "audit_image_omics": "**Not found**",
        "audit_organs": "**Not found**",
        "audit_downstream": "**Not found**",
        "audit_cohorts": "**Not found**",
        "audit_notes": "**A distinct KRONOS2 primary paper/model card could not be located and verified in this sweep. No KRONOS values were carried over.**",
        "paper_title": "A foundation model for spatial proteomics",
        "paper_author": "Shaban"
      },
      {
        "name": "GigaTIME-Flash",
        "year": 2026,
        "data": "Real-world Providence cohort",
        "idea": "Efficient spatial proteomics prediction from H&E",
        "github": "",
        "hf": "https://huggingface.co/prov-gigatime/gigatime-flash",
        "paper": "https://arxiv.org/abs/2607.18218",
        "audit_wsis": "**Not found**",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Spatial-proteomics prediction supervision; **exact paired count Not found**",
        "audit_organs": "Not found",
        "audit_downstream": "Tumor immune microenvironment/spatial-proteomics prediction; exact task count Not found",
        "audit_cohorts": "Large real-world clinical data; exact source count Not found",
        "audit_notes": "Uses the compact GigaPath-Flash visual backbone.",
        "paper_title": "GigaPath-Flash and GigaTIME-Flash: Efficient Pathology Foundation Models for Whole-Slide and Tumor Microenvironment Analysis",
        "paper_author": "Usuyama"
      }
    ]
  },
  {
    "category": "Foundation Model Adaptation & Distillation",
    "models": [
      {
        "name": "H0-mini",
        "type": "Single-FM Distillation",
        "year": 2024,
        "data": "",
        "idea": "",
        "github": "",
        "hf": "",
        "paper": ""
      },
      {
        "name": "SEAL",
        "year": 2026,
        "data": "---",
        "idea": "---",
        "github": "https://github.com/mahmoodlab/SEAL/",
        "hf": "https://huggingface.co/MahmoodLab/SEAL",
        "paper": "https://arxiv.org/abs/2602.14177",
        "audit_wsis": "N/A \u2014 parameter-efficient vision\u2013omics adaptation",
        "audit_patches": "Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "**>700K paired spatial-transcriptomics gene-expression spot\u2013tissue-region examples**",
        "audit_organs": "**14 organs**",
        "audit_downstream": "**53 tasks = 38 slide-level + 15 patch-level**; molecular status, pathways, treatment response, gene-expression prediction, gene\u2192image retrieval",
        "audit_cohorts": "Exact institution/cohort count Not found",
        "audit_notes": "ST-guided fine-tuning of existing PFMs rather than a wholly new from-scratch visual encoder.",
        "paper_title": "Towards Spatial Transcriptomics-driven Pathology Foundation Models",
        "paper_author": "Hemker",
        "type": "Vision\u2013omics adaptation"
      },
      {
        "name": "Phaet",
        "year": 2026,
        "data": "---",
        "idea": "Robustness-tuned Phikon-v2",
        "github": "",
        "hf": "https://huggingface.co/wearewaiv/phaet",
        "paper": "https://arxiv.org/abs/2607.22861",
        "audit_wsis": "N/A as a new from-scratch corpus; base = Phikon-v2",
        "audit_patches": "Fine-tuning size Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Fine-tuning coverage Not found",
        "audit_downstream": "PathoROB; HEST (9 cancer/ST tasks); THUNDER (6 task types over 16 datasets); 63 Patho-Bench tasks used in this study",
        "audit_cohorts": "PathoROB includes 34 medical centers; fine-tuning-site count Not found",
        "audit_notes": "Robustness-tuned Phikon-v2, not an independently pretrained FM.",
        "paper_title": "Robustifying pathology foundation models via fine-tuning",
        "paper_author": "Filiot",
        "type": "Robustness adaptation"
      },
      {
        "name": "Mascaret",
        "year": 2026,
        "data": "---",
        "idea": "Robustness-tuned Midnight-12k",
        "github": "",
        "hf": "https://huggingface.co/wearewaiv/mascaret",
        "paper": "https://arxiv.org/abs/2607.22861",
        "audit_wsis": "N/A as a new from-scratch corpus; base = Midnight-12k",
        "audit_patches": "Fine-tuning size Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Fine-tuning coverage Not found",
        "audit_downstream": "Same robustness suites as Phaet: PathoROB, HEST, THUNDER, Patho-Bench subset",
        "audit_cohorts": "PathoROB includes 34 medical centers; fine-tuning-site count Not found",
        "audit_notes": "Robustness-tuned Midnight-12k.",
        "paper_title": "Robustifying pathology foundation models via fine-tuning",
        "paper_author": "Filiot",
        "type": "Robustness adaptation"
      }
    ]
  },
  {
    "category": "Multi-FM Integration & Distillation",
    "models": [
      {
        "name": "GPFM",
        "year": 2025,
        "data": "190M tiles, 96K WSIs",
        "idea": "Multi-teacher distillation",
        "github": "https://github.com/birkhoffkiki/GPFM/",
        "hf": "",
        "paper": "https://arxiv.org/abs/2407.18449",
        "audit_wsis": "**~86K public H&E WSIs**",
        "audit_patches": "**190M images**",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "**34 major tissue types**",
        "audit_downstream": "**39 specific tasks across 6 clinical task types**",
        "audit_cohorts": "Public datasets; exact source-institution count Not found",
        "audit_notes": "Expert + self knowledge distillation. **Primary source says ~86K, not 96K WSIs.**",
        "paper_title": "Towards A Generalizable Pathology Foundation Model via Unified Knowledge Distillation",
        "paper_author": "Ma"
      },
      {
        "name": "COBRA",
        "year": 2025,
        "data": "3048 WSIs",
        "idea": "Multi-FM representation integration",
        "github": "https://github.com/KatherLab/COBRA",
        "hf": "https://huggingface.co/KatherLab/COBRA",
        "paper": "https://arxiv.org/abs/2411.13623",
        "audit_wsis": "**Not found**",
        "audit_patches": "Uses tile embeddings from several PFMs; new raw-tile count Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "**Not found**",
        "audit_cohorts": "**Not found**",
        "audit_notes": "The frequently cited 3,048-WSI number was not independently recovered in the primary text available during this audit, so I have not repeated it as verified.",
        "paper_title": "Unsupervised Foundation Model-Agnostic Slide-Level Representation Learning",
        "paper_author": "Lenz"
      },
      {
        "name": "ELF",
        "year": 2025,
        "data": "53K WSIs (20 anatomical sites)",
        "idea": "Ensemble learning",
        "github": "https://github.com/lilab-stanford/ELF",
        "hf": "",
        "paper": "https://arxiv.org/abs/2508.16085",
        "audit_wsis": "**Not found**",
        "audit_patches": "Integrates outputs from 5 PFMs; raw tile count Not found",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "**Not found**",
        "audit_downstream": "**Not found**",
        "audit_cohorts": "**Not found**",
        "audit_notes": "Likewise, the seed-list 53K-WSI/20-site values remain unverified under the strict extraction rule.",
        "paper_title": "Ensemble learning of foundation models for precision oncology",
        "paper_author": "Luo"
      },
      {
        "name": "Shazam",
        "year": 2026,
        "data": "Fuses 5 models (UNI 2, Virchow2, H-optimus-1, Prov-Gigapath, Phikon-v2)",
        "idea": "Adaptive integration/distillation",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2503.00736",
        "audit_wsis": "N/A \u2014 no standalone fixed pretraining corpus",
        "audit_patches": "N/A \u2014 online integration of pretrained FM representations",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "**4 task families:** spatial-transcriptomics prediction, survival prognosis, tile classification, VQA",
        "audit_cohorts": "Dataset-dependent; exact aggregate number Not found",
        "audit_notes": "Adaptive online expert weighting/distillation; categorically different from offline corpus distillation.",
        "paper_title": "Unifying Multiple Foundation Models for Advanced Computational Pathology",
        "paper_author": "Lei"
      },
      {
        "name": "ALICE",
        "year": 2026,
        "data": "24.9M tiles + 155K high-res images",
        "idea": "Agglomerative distillation",
        "github": "https://github.com/WonderLandxD/ALICE",
        "hf": "",
        "paper": "https://arxiv.org/pdf/2607.09526",
        "audit_wsis": "**Not found**",
        "audit_patches": "**24,985,184 tile-level pathology images + 155,604 high-resolution images**",
        "audit_image_text": "Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "Not found",
        "audit_downstream": "**96 downstream tasks across 21 task scenarios**",
        "audit_cohorts": "**48 evaluation data sources**; pretraining institution count Not found",
        "audit_notes": "Agglomerative distillation from **8** vision-only, VLM and slide-level teachers.",
        "paper_title": "ALICE: Learning a General-Purpose Pathology Foundation Model from Vision, Vision-Language, and Slide-Level Experts",
        "paper_author": "Li"
      },
      {
        "name": "ASTRA",
        "year": 2026,
        "data": "10.3K WSIs (CHTN cohort)",
        "idea": "MoE fusion/alignment",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2604.22846",
        "audit_wsis": "**Not found**; developed on 10,359 CHTN WSIs",
        "audit_patches": "Raw-tile count Not found; integrates existing FM representations",
        "audit_image_text": "Structured pathology prompts used, count Not found",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "**16 tumor types**",
        "audit_downstream": "4 main task settings: 4-category classification, 3-class solid-tumor typing, 16-class cancer typing, text-guided tumor localization",
        "audit_cohorts": "CHTN development 10,359 WSIs + external TCGA 1,686 WSIs",
        "audit_notes": "\u201cDeveloped on\u201d is preserved rather than relabeled as \u201cpretrained on.\u201d",
        "paper_title": "Unified Multi-Foundation-Model Slide Representation for Pan-Cancer Recognition and Text-Guided Tumor Localization",
        "paper_author": "Wang"
      }
    ]
  },
  {
    "category": "Segmentation & Interactive Foundation Models",
    "models": [
      {
        "name": "VISTA-PATH",
        "year": 2026,
        "data": "1.65M triplets (Image + Mask + Text)",
        "idea": "Interactive Class-Aware Segmentation",
        "github": "https://github.com/zhihuanglab/VISTA-PATH",
        "hf": "",
        "paper": "https://arxiv.org/abs/2601.16451",
        "audit_wsis": "**Not found**",
        "audit_patches": "**>1.6M image\u2013mask\u2013text triplets**",
        "audit_image_text": "**>1.6M triplets contain a text component**",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "Not found",
        "audit_organs": "**9 organs; 93 tissue classes**",
        "audit_downstream": "Held-out/external semantic segmentation plus TME quantitative/survival analyses; exact scalar benchmark count Not found",
        "audit_cohorts": "Multiple external/held-out datasets; exact site count Not found",
        "audit_notes": "Triplet-based corpus rather than WSI-count-based pretraining.",
        "paper_title": "VISTA-PATH: An interactive foundation model for pathology image segmentation and quantitative analysis in computational pathology",
        "paper_author": "Liang"
      }
    ]
  },
  {
    "category": "Generative Foundation Models",
    "models": [
      {
        "name": "MuPD",
        "year": 2026,
        "data": "100M patches",
        "idea": "Multimodal Pathology Diffusion Model",
        "github": "https://github.com/lilab-stanford/MUPAD",
        "hf": "https://huggingface.co/collections/xiangjx/mupad-multimodal-pathology-diffusion-model",
        "paper": "https://arxiv.org/abs/2604.03635",
        "audit_wsis": "**Not found**",
        "audit_patches": "**100M histology patches**",
        "audit_image_text": "**1.6M text\u2013histology pairs**",
        "audit_wsi_report": "Not found",
        "audit_image_omics": "**10.8M RNA\u2013histology pairs**",
        "audit_organs": "**34 human organs**",
        "audit_downstream": "Text-conditioned generation, image-to-image generation, RNA-conditioned generation, virtual staining, synthetic-data augmentation; no single explicit scalar total",
        "audit_cohorts": "Not found",
        "audit_notes": "Multimodal pathology diffusion transformer; synthetic images are also assessed as augmentation data.",
        "paper_title": "A Generative Foundation Model for Multimodal Histopathology",
        "paper_author": "Xiang"
      }
    ]
  },
  {
    "category": "Foundation Model Benchmarking",
    "models": [
      {
        "name": "EVA",
        "year": 2024,
        "data": "Slide & Patch",
        "idea": "Standardized framework for systematic evaluation and comparison of PFMs",
        "github": "https://github.com/kaiko-ai/eva",
        "hf": "",
        "paper": "https://openreview.net/forum?id=FNBQOPj18N",
        "audit_wsis": "N/A",
        "audit_patches": "N/A",
        "audit_image_text": "N/A",
        "audit_wsi_report": "N/A",
        "audit_image_omics": "N/A",
        "audit_organs": "Not found",
        "audit_downstream": "Standardized patch-/slide-level FM evaluation framework; exact task total Not found",
        "audit_cohorts": "Not found",
        "audit_notes": "Benchmark rather than pretrained model.",
        "paper_title": "eva: Evaluation framework for pathology foundation models",
        "paper_author": "kaiko.ai"
      },
      {
        "name": "Patho-Bench",
        "year": 2025,
        "data": "Slide",
        "idea": "Open-source benchmarking toolkit with standardized datasets and reproducible evaluation pipelines",
        "github": "https://github.com/mahmoodlab/Patho-Bench",
        "hf": "",
        "paper": "https://arxiv.org/pdf/2502.06750",
        "audit_wsis": "N/A",
        "audit_patches": "N/A",
        "audit_image_text": "N/A",
        "audit_wsi_report": "N/A",
        "audit_image_omics": "N/A",
        "audit_organs": "Multi-organ oncology; exact count Not found",
        "audit_downstream": "**95 tasks across 7 categories:** morphological subtyping, TME characterization, tumor grading, molecular subtyping, mutation prediction, treatment response, survival",
        "audit_cohorts": "Multiple public datasets; exact institution count Not found",
        "audit_notes": "Open-source standardized slide-level benchmarking framework; the 95-task scope is also explicitly referenced by the Phaet/Mascaret evaluation.",
        "paper_title": "Accelerating Data Processing and Benchmarking of AI Models for Pathology",
        "paper_author": "Zhang"
      },
      {
        "name": "QuIIL-PathBench",
        "year": 2025,
        "data": "Patch",
        "idea": "Systematically benchmarks PFMs by evaluating patch-level representations",
        "github": "https://github.com/QuIIL/BenchmarkingPathologyFoundationModels",
        "hf": "",
        "paper": "https://arxiv.org/abs/2410.16038",
        "audit_wsis": "N/A",
        "audit_patches": "N/A",
        "audit_image_text": "N/A",
        "audit_wsi_report": "N/A",
        "audit_image_omics": "N/A",
        "audit_organs": "Not found",
        "audit_downstream": "Patch-level PFM benchmarking; exact task/dataset number Not found",
        "audit_cohorts": "Not found",
        "audit_notes": "Benchmark, not a pretraining corpus.",
        "paper_title": "Benchmarking Pathology Foundation Models: Adaptation Strategies and Scenarios",
        "paper_author": "Lee"
      },
      {
        "name": "Clinical Benchmark",
        "year": 2025,
        "data": "Slide",
        "idea": "Clinical benchmark with MSHS and MSKCC datasets covering disease detection and biomarker prediction",
        "github": "https://github.com/sinai-computational-pathology/SSL_tile_benchmarks#automated-external-benchmarking",
        "hf": "",
        "paper": "https://www.nature.com/articles/s41467-025-58796-1.pdf",
        "audit_wsis": "N/A",
        "audit_patches": "**9,528 evaluation H&E WSIs** \u2014 not pretraining patches",
        "audit_image_text": "N/A",
        "audit_wsi_report": "N/A",
        "audit_image_omics": "N/A",
        "audit_organs": "**4 cancer types**",
        "audit_downstream": "**31 weakly supervised tasks: 5 morphology + 19 biomarker + 7 prognostication**",
        "audit_cohorts": "**13 cohorts; 6,818 patients**; includes TCGA/CPTAC and external cohorts such as DACHS, Bern, Kiel and IEO",
        "audit_notes": "Evaluates **19 FMs + 14 ensembles**. Evaluation slides must not be mistaken for pretraining data.",
        "paper_title": "A clinical benchmark of public self-supervised pathology foundation models",
        "paper_author": "Campanella"
      },
      {
        "name": "PathBench",
        "year": 2025,
        "data": "Slide & Patch",
        "idea": "Leakage-free multi-center clinical benchmark spanning multiple tasks, with a live public leaderboard",
        "github": "https://github.com/birkhoffkiki/PathBench",
        "hf": "",
        "website": "https://birkhoffkiki.github.io/PathBench/",
        "paper": "https://arxiv.org/abs/2505.20202",
        "audit_wsis": "N/A",
        "audit_patches": "N/A",
        "audit_image_text": "N/A",
        "audit_wsi_report": "N/A",
        "audit_image_omics": "N/A",
        "audit_organs": "Not found",
        "audit_downstream": "Leakage-free slide/patch multi-center clinical benchmark; exact task count Not found",
        "audit_cohorts": "Multi-center; exact count Not found",
        "audit_notes": "Public leaderboard; benchmark rather than model.",
        "paper_title": "PathBench: A comprehensive comparison benchmark for pathology foundation models towards precision oncology",
        "paper_author": "Ma"
      },
      {
        "name": "Stanford PathBench",
        "year": 2026,
        "data": "Slide & Patch",
        "idea": "Comprehensive benchmark of 32 PFMs across 41 tasks with a public leaderboard",
        "github": "",
        "hf": "",
        "paper": "https://www.nature.com/articles/s41467-026-76004-6",
        "audit_wsis": "N/A",
        "audit_patches": "Evaluation uses slide- and patch-level TCGA/CPTAC/external data; exact total Not found",
        "audit_image_text": "N/A",
        "audit_wsi_report": "N/A",
        "audit_image_omics": "N/A",
        "audit_organs": "Multiple tissues; exact count Not found",
        "audit_downstream": "**32 foundation models** evaluated across slide- and patch-level task categories; exact task count Not found in the primary abstract I could verify",
        "audit_cohorts": "TCGA, CPTAC and external/OOD datasets; exact cohort count Not found",
        "audit_notes": "Published July 24, 2026; decision-level ensembling also evaluated. The seed-list \u201c41 tasks\u201d figure is not asserted here because I did not independently recover it from the accessible primary source.",
        "paper_title": "A benchmark study of vision and pathology foundation models for computational pathology",
        "paper_author": "Bareja"
      }
    ]
  },
  {
    "category": "Survey",
    "models": [
      {
        "name": "Xiong et al.",
        "year": 2025,
        "data": "N/A",
        "idea": "Comprehensive survey of progress and future directions in pathology foundation models",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2504.04045",
        "paper_title": "A Survey of Pathology Foundation Model: Progress and Future Directions",
        "paper_author": "Xiong",
        "audit_wsis": "N/A",
        "audit_patches": "N/A",
        "audit_image_text": "N/A",
        "audit_wsi_report": "N/A",
        "audit_image_omics": "N/A",
        "audit_organs": "N/A",
        "audit_downstream": "N/A",
        "audit_cohorts": "N/A",
        "audit_notes": "Survey paper"
      },
      {
        "name": "Chanda et al.",
        "year": 2024,
        "data": "N/A",
        "idea": "Survey on Foundation and Vision-Language Models",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2408.14496",
        "paper_title": "A New Era in Computational Pathology: A Survey on Foundation and Vision-Language Models",
        "paper_author": "Chanda",
        "audit_wsis": "N/A",
        "audit_patches": "N/A",
        "audit_image_text": "N/A",
        "audit_wsi_report": "N/A",
        "audit_image_omics": "N/A",
        "audit_organs": "N/A",
        "audit_downstream": "N/A",
        "audit_cohorts": "N/A",
        "audit_notes": "Survey paper"
      },
      {
        "name": "Li et al.",
        "year": 2025,
        "data": "N/A",
        "idea": "Survey covering datasets, adaptation strategies, and evaluation tasks",
        "github": "",
        "hf": "",
        "paper": "https://link.springer.com/article/10.1007/s10115-026-02806-1",
        "paper_title": "A survey on computational pathology foundation models: datasets, adaptation strategies, and evaluation tasks",
        "paper_author": "Li",
        "audit_wsis": "N/A",
        "audit_patches": "N/A",
        "audit_image_text": "N/A",
        "audit_wsi_report": "N/A",
        "audit_image_omics": "N/A",
        "audit_organs": "N/A",
        "audit_downstream": "N/A",
        "audit_cohorts": "N/A",
        "audit_notes": "Survey paper"
      }
    ]
  }
];
