const modelData = [
  {
    "category": "Tile-Level Vision Foundation Models",
    "models": [
      {
        "name": "BRAVE",
        "year": 2026,
        "data": "57,271 WSIs",
        "idea": "Breast-adaptive pathology foundation model",
        "stains": "H&E",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2605.08207",
        "audit_wsis": "101,638 WSIs (total resource)",
        "audit_organs": "Breast",
        "audit_downstream": "34 tasks in 82 cohorts",
        "audit_cohorts": "32 sources across Asia, Europe and North America",
        "paper_title": "A Breast Vision Pathology Foundation Model for Real-world Clinical Utility",
        "paper_author": "Xu"
      },
      {
        "name": "CTransPath",
        "year": 2022,
        "data": "32K+ WSIs",
        "idea": "SRCL with hybrid CNN-ViT",
        "stains": "H&E",
        "github": "https://github.com/Xiyue-Wang/TransPath",
        "hf": "https://drive.google.com/file/d/1DoDx_70_TLj98gTf6YTXnu4tFhsFocDX/view",
        "paper": "https://www.sciencedirect.com/science/article/pii/S1361841522002043",
        "audit_wsis": ">30,000",
        "audit_patches": "~15M patches",
        "audit_organs": ">25 anatomic sites; 32 cancer subtypes",
        "audit_downstream": "5 task families: patch retrieval, supervised patch classification, weakly supervised WSI classification, mitosis detection, colorectal gland segmentation; 9 public datasets",
        "audit_cohorts": "Pretraining sources TCGA + PAIP",
        "audit_notes": "Public-source pathology corpus; SRCL hybrid CNN\u2013ViT.",
        "paper_title": "Transformer-based unsupervised contrastive learning for histopathological image classification",
        "paper_author": "Wang"
      },
      {
        "name": "REMEDIS",
        "year": 2023,
        "data": "29K+ WSIs",
        "idea": "BiT + SimCLR Pretraining",
        "stains": "H&E",
        "github": "",
        "hf": "",
        "paper": "https://doi.org/10.1038/s41551-023-01049-7",
        "audit_wsis": "29,018",
        "audit_patches": "50M pathology images",
        "audit_cohorts": "TCGA for pathology SSL",
        "audit_notes": "The 29,018/50M figures are explicitly restated in the Prov-GigaPath methods comparison; REMEDIS also covers non-pathology medical imaging.",
        "paper_title": "Robust and data-efficient generalization of self-supervised machine learning for diagnostic imaging",
        "paper_author": "Azizi"
      },
      {
        "name": "Lunit",
        "year": 2023,
        "data": "36K+ WSI",
        "idea": "Pathology-Specific SSL Pretraining",
        "stains": "H&E",
        "github": "https://github.com/lunit-io/benchmark-ssl-pathology",
        "hf": "https://huggingface.co/1aurent/vit_small_patch8_224.lunit_dino",
        "paper": "https://arxiv.org/abs/2212.04690",
        "audit_wsis": "36,666",
        "audit_patches": "32,578,557 patches",
        "audit_organs": "Multiple cancers",
        "audit_downstream": "2 task types over 5 datasets: classification on BACH, CRC, MHIST, PatchCamelyon; nuclei instance segmentation/classification on CoNSeP",
        "audit_cohorts": "2 pretraining sources: TCGA 20,994 WSIs + internal TULIP 15,672",
        "audit_notes": "19,000,069 TCGA + 13,578,488 TULIP patches; 20\u00d7/40\u00d7.",
        "paper_title": "Benchmarking Self-Supervised Learning on Diverse Pathology Datasets",
        "paper_author": "Kang"
      },
      {
        "name": "Phikon",
        "year": 2023,
        "data": "6,093 WSIs",
        "idea": "iBOT Masked Image Pretraining",
        "stains": "H&E",
        "github": "https://github.com/owkin/HistoSSLscaling/",
        "hf": "https://huggingface.co/owkin/phikon",
        "paper": "https://www.medrxiv.org/content/10.1101/2023.07.21.23292757v2",
        "audit_wsis": "6,093 TCGA WSIs",
        "audit_patches": ">40M pan-cancer tiles",
        "audit_organs": "16 cancer types",
        "audit_downstream": "patch- and WSI-level cancer tasks",
        "audit_cohorts": "TCGA public source",
        "audit_notes": "iBOT pretraining; official Owkin material reports >40M images. The 6,093-slide PanCancer corpus is independently specified by the H0-mini official material.",
        "paper_title": "Scaling Self-Supervised Learning for Histopathology with Masked Image Modeling",
        "paper_author": "Filiot"
      },
      {
        "name": "PathoDuet",
        "year": 2024,
        "data": "11K WSIs",
        "idea": "Cross-Scale Cross-Stain Pretraining",
        "stains": "H&E + IHC (paired)",
        "github": "https://github.com/openmedlab/PathoDuet",
        "hf": "",
        "paper": "https://www.sciencedirect.com/science/article/pii/S1361841524002147",
        "audit_wsis": "~11,000",
        "audit_image_omics": "Paired H&E–IHC used",
        "audit_organs": "Pan-cancer",
        "audit_downstream": "Patch classification, WSI classification, PD-L1 expression classification, cross-site IHC tumor identification",
        "audit_cohorts": "TCGA, HyReCo, BCI and downstream public datasets",
        "audit_notes": "Cross-scale/cross-stain learning; exact unique pretraining patch total not recovered.",
        "paper_title": "PathoDuet: Foundation Models for Pathological Slide Analysis of H&E and IHC Stains",
        "paper_author": "Hua"
      },
      {
        "name": "RudolfV",
        "year": 2024,
        "data": "134K WSIs, 58 tissue types",
        "idea": "Pathologist-curated data and expertise",
        "stains": "129 histochemical & IHC stain modalities",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2401.04079",
        "audit_organs": "58 tissue types; 129 histochemical/IHC stain modalities",
        "audit_downstream": "Tumor-microenvironment profiling, biomarker evaluation, reference-case search",
        "audit_cohorts": ">15 laboratories across Europe/US",
        "audit_notes": "The often-repeated seed-list slide total was not visible in the primary text I could verify, so it is deliberately not reproduced.",
        "paper_title": "RudolfV: A Foundation Model by Pathologists for Pathologists",
        "paper_author": "Dippel"
      },
      {
        "name": "PLUTO",
        "year": 2024,
        "data": "195M tiles",
        "idea": "Lightweight multi-scale representation",
        "stains": "H&E + IHC",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2405.07905",
        "audit_wsis": "158,852 WSIs (from 50+ source sites)",
        "audit_patches": "195M image tiles",
        "audit_organs": "16 tissue groups; 28 disease areas",
        "audit_downstream": "Instance segmentation, tile classification, slide-level prediction across public (NSCLC, CRC-100K, Camelyon17-WILDS, GlaS, PanNuke) + proprietary benchmarks",
        "audit_cohorts": "50+ source sites (TCGA, MSKCC, MGH, BWH, GTEx, NCT Biobank, UMM)",
        "audit_notes": "Pathology-Universal Transformer; 158,852 WSIs / 195M tiles from 50+ sites; multi-scale (FlexiViT) representation.",
        "paper_title": "PLUTO: Pathology-Universal Transformer",
        "paper_author": "Juyal"
      },
      {
        "name": "UNI",
        "year": 2024,
        "data": "100M tiles, 100K WSIs",
        "idea": "General-purpose DINOv2 on 100K WSIs",
        "stains": "H&E",
        "github": "https://github.com/mahmoodlab/UNI",
        "hf": "https://huggingface.co/MahmoodLab/UNI",
        "paper": "https://doi.org/10.1038/s41591-024-02857-3",
        "audit_wsis": ">100K WSIs",
        "audit_patches": ">100M images",
        "audit_organs": "20 major tissue types",
        "audit_downstream": "34 representative CPath tasks",
        "audit_cohorts": "Two hospitals plus GTEx are reported as principal sources",
        "audit_notes": ">77 TB diagnostic H&E; public/private mix.",
        "paper_title": "Towards a general-purpose foundation model for computational pathology",
        "paper_author": "Chen"
      },
      {
        "name": "Virchow",
        "year": 2024,
        "data": "1.5M WSIs, 100K patients",
        "idea": "Clinical-grade pan-cancer detection",
        "stains": "H&E",
        "github": "",
        "hf": "https://huggingface.co/paige-ai/Virchow",
        "paper": "https://doi.org/10.1038/s41591-024-03141-0",
        "audit_wsis": "~1.5M H&E WSIs",
        "audit_patches": "~2B sampled training tiles; ~13B available tissue tiles",
        "audit_organs": "17 high-level tissue groups",
        "audit_downstream": "Pan-cancer detection across 17 types, rare-cancer detection across 7 rare types, tile benchmarks and slide biomarker prediction",
        "audit_cohorts": "Pretraining at MSKCC; external evaluation includes 7 additional clinical datasets",
        "audit_notes": "~100K patients; **2B is sampled training instances, not unique patches**.",
        "paper_title": "A foundation model for clinical-grade computational pathology and rare cancers detection",
        "paper_author": "Vorontsov"
      },
      {
        "name": "Virchow2",
        "year": 2024,
        "data": "3.1M WSIs",
        "idea": "1.9B parameters, mixed magnification",
        "stains": "H&E + IHC (mixed magnification)",
        "github": "",
        "hf": "https://huggingface.co/paige-ai/Virchow2",
        "paper": "https://arxiv.org/abs/2408.00738",
        "audit_wsis": "3.1M",
        "audit_organs": "Nearly 200 tissue types",
        "audit_downstream": "12 tile-level downstream tasks reported",
        "audit_cohorts": "225,401 patients",
        "audit_notes": "Mixed 5\u00d7/10\u00d7/20\u00d7/40\u00d7; H&E + IHC diversity.",
        "paper_title": "Virchow2: Scaling Self-Supervised Mixed Magnification Models in Pathology",
        "paper_author": "Zimmermann"
      },
      {
        "name": "Hibou",
        "year": 2024,
        "data": "1M WSIs",
        "idea": "Open-source DINOv2 architecture",
        "stains": "H&E + IHC",
        "github": "https://github.com/histai/hibou",
        "hf": "https://huggingface.co/histai/hibou-L",
        "paper": "https://arxiv.org/abs/2406.05074",
        "audit_wsis": ">1M",
        "audit_organs": "Diverse tissues",
        "audit_downstream": "Patch- and slide-level benchmarks",
        "audit_cohorts": "Proprietary corpus",
        "audit_notes": "I retained only the >1M number explicitly visible in the primary description.",
        "paper_title": "Hibou: A Family of Foundational Vision Transformers for Pathology",
        "paper_author": "Nechaev"
      },
      {
        "name": "BEPH",
        "year": 2024,
        "data": "11M tiles",
        "idea": "BEiT-based masked image modeling",
        "stains": "H&E",
        "github": "https://github.com/Zhcyoung/BEPH",
        "hf": "https://drive.google.com/file/d/19Fu3dw3G4i2gPXijzrxfaQ2D_xcqNdNz/view",
        "paper": "https://www.nature.com/articles/s41467-025-57587-y",
        "audit_patches": "~11M unlabeled pathology images",
        "audit_organs": "32 TCGA cancer types",
        "audit_downstream": "3 task families: patch diagnosis (BreakHis), WSI subtype classification (TCGA-BRCA), survival prediction (TCGA-CRC)",
        "audit_cohorts": "TCGA (all pretraining via GDC); validation on public datasets (e.g., BreakHis)",
        "audit_notes": "BEiT-style masked-image pretraining on ~11M TCGA tiles (224x224 @ 40x), 32 cancer types.",
        "paper_title": "A foundation model for generalizable cancer diagnosis and survival prediction from histopathological images",
        "paper_author": "Yang"
      },
      {
        "name": "Atlas",
        "year": 2025,
        "data": "1.2M WSIs (Mayo + Charit\u00e9)",
        "idea": "Efficient RudolfV-based model",
        "stains": "H&E, IHC, special stains (100+ types)",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2501.05409",
        "audit_wsis": "1.2M",
        "audit_patches": "3.4 billion image tiles",
        "audit_organs": "70+ tissue/organ types; 100+ staining types; 7 scanner types",
        "audit_downstream": "21 public benchmark datasets (12 molecular + 9 morphology tasks)",
        "audit_cohorts": "Mayo Clinic + Charite (2 institutions); 490K cases -> 1.2M WSIs",
        "audit_notes": "1.2M WSIs from 490K cases (Mayo + Charite); 3.4B tiles; 70+ tissues, 100+ stains, 7 scanners. RudolfV-based.",
        "paper_title": "Atlas: A Novel Pathology Foundation Model by Mayo Clinic, Charit\\'e, and Aignostics",
        "paper_author": "Alber"
      },
      {
        "name": "Midnight",
        "year": 2025,
        "data": "12K / 92K WSIs",
        "idea": "Data-efficient DINOv2 optimization",
        "stains": "H&E",
        "github": "https://github.com/kaiko-ai/midnight",
        "hf": "",
        "paper": "https://arxiv.org/abs/2504.05186",
        "audit_wsis": "12K / 92K",
        "audit_patches": "384M sampled tile instances over training; not a fixed unique corpus",
        "audit_organs": "TCGA: 32 cancer types; NKI extension: 31 organs",
        "audit_downstream": "BACH, BRACS, BreaKHis, CRC100K, Gleason TMA, MHIST, PatchCamelyon, Camelyon16, PANDA, CoNSeP, MoNuSAC, HEST; HEST contains 9 ST gene-expression tasks",
        "audit_cohorts": "TCGA + NKI; NKI includes 10,141 patients",
        "audit_notes": "Midnight-12k is public TCGA; Midnight-92k adds 80K proprietary NKI slides; online tile extraction.",
        "paper_title": "Training state-of-the-art pathology foundation models with orders of magnitude less data",
        "paper_author": "Karasikov"
      },
      {
        "name": "H-optimus-0",
        "year": 2025,
        "data": "500K WSIs",
        "idea": "SSL Pretraining, FM Distillation",
        "stains": "H&E",
        "github": "https://github.com/bioptimus/releases/tree/main/models/h-optimus/v0",
        "hf": "https://huggingface.co/bioptimus/H-optimus-0",
        "paper": "https://arxiv.org/abs/2501.16239v1",
        "audit_wsis": ">500K proprietary H&E WSIs",
        "audit_downstream": "Examples include mutation prediction, survival prediction, tissue classification",
        "audit_notes": "1.1B-parameter tile FM; private corpus.",
        "paper_title": "Distilling foundation models for robust and efficient models in digital pathology",
        "paper_author": "Filiot"
      },
      {
        "name": "PathOrchestra",
        "year": 2025,
        "data": "27K WSIs, 100 tasks",
        "idea": "Evaluated on 112 clinical tasks",
        "stains": "H&E, IHC, special stains (>35 types)",
        "github": "",
        "hf": "https://huggingface.co/AI4Pathology/PathOrchestra",
        "paper": "https://arxiv.org/abs/2503.24345",
        "audit_wsis": "**287,424 H&E WSIs**",
        "audit_organs": "21 tissues/organs/systems",
        "audit_downstream": "**112 tasks: 61 WSI + 51 ROI**; slide preprocessing 12, pan-cancer 3, lesion identification 15, cancer subtyping 36, biomarker evaluation 36, gene-expression assessment 10",
        "audit_cohorts": "**3 pretraining centers**; evaluation uses 51 public + 61 private datasets",
        "audit_notes": "Evaluation corpus is 27,755 WSIs + 9,415,729 ROIs; >35 stains and >50 genes.",
        "paper_title": "PathOrchestra: A Comprehensive Foundation Model for Computational Pathology with Over 100 Diverse Clinical-Grade Tasks",
        "paper_author": "Yan"
      },
      {
        "name": "GenBio-PathFM",
        "year": 2026,
        "data": "177K WSIs",
        "idea": "JEDI (JEPA+DINO) dual-stage learning",
        "stains": "H&E",
        "github": "https://github.com/genbio-ai/genbio-pathfm",
        "hf": "https://huggingface.co/genbio-ai/genbio-pathfm",
        "paper": "https://www.biorxiv.org/content/10.64898/2026.03.17.712534v1",
        "audit_downstream": "THUNDER, HEST, PathoROB benchmark families",
        "audit_cohorts": "Public-only training",
        "audit_notes": "1.1B-parameter model trained exclusively on publicly available data. JEDI = DINO (stage 1) + JEPA (stage 2). SOTA on THUNDER, HEST, PathoROB. Exact pretraining WSI/patch counts not recovered from primary text.",
        "paper_title": "GenBio-PathFM: A State-of-the-Art Foundation Model for Histopathology",
        "paper_author": "Kapse"
      },
      {
        "name": "RudolfV2",
        "year": 2026,
        "data": "300K+ WSIs",
        "idea": "Robust Multi-Scale SSL Pretraining",
        "github": "",
        "hf": "https://huggingface.co/Aignostics/RudolfV-2",
        "paper": "https://cdn.prod.website-files.com/67adb01f31489469b513304a/6a74e2f9f1d4aef06489a3f1_RudolfV_2_260806.pdf",
        "audit_wsis": "~300K WSIs",
        "audit_downstream": "Tissue/tumor classification, grading, biomarker prediction, MIL slide-level modeling; exact benchmark count not on card",
        "audit_notes": "~300K WSIs pretraining. Open-weights family: RudolfV2 (ViT-g, 1.1B params), RudolfV2-B (ViT-B, 86M), RudolfV2-S (ViT-S, 22M). Robust multi-scale SSL.",
        "paper_title": "RudolfV 2: A Family of Robust and Efficient Open-Weights Pathology Foundation Models",
        "paper_author": "Milbich"
      },
      {
        "name": "Atlas 2",
        "year": 2026,
        "data": "5.5M WSIs",
        "idea": "2B params, robust evaluation on 80 benchmarks",
        "stains": "H&E, IHC, special stains (100+ types)",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/pdf/2601.05148",
        "audit_wsis": "**5.5M WSIs**",
        "audit_organs": "70+ tissue types; 100+ staining types",
        "audit_downstream": "**80 public benchmarks**",
        "audit_cohorts": "3 institutions: Charit\u00e9, LMU Munich, Mayo Clinic",
        "audit_notes": "~490K cases and 7 scanner types reported by official project material.",
        "paper_title": "Atlas 2 -- Foundation models for clinical deployment",
        "paper_author": "Alber"
      },
      {
        "name": "GRACE",
        "year": 2026,
        "data": "48K WSIs",
        "idea": "Gastric-specific foundation model",
        "stains": "Primarily H&E",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2606.04792",
        "audit_wsis": "25,719 biopsy/surgical WSIs (LoRA continued pretraining); 48,364 total dev/validation WSIs from 37,493 patients",
        "audit_patches": "107 million patches (pretraining subset)",
        "audit_organs": "Stomach/gastric, 1 organ focus",
        "audit_downstream": "28 tasks (28 internal, 11 external, 33 prospective cohorts): precancerous lesions, histopathologic assessment, molecular profiling, prognosis",
        "audit_cohorts": "9 hospitals (H1-H9); 72 validation cohorts; 37,493 dev patients; downstream 22,645 WSIs / 11,774 patients",
        "audit_notes": "GRACE = LoRA continued-pretraining on 25,719 gastric WSIs (107M patches); 48,364 total dev/validation WSIs (37,493 patients) across 9 hospitals. Gastric-specific.",
        "paper_title": "A Pathology Foundation Model for Gastric Cancer with Real-World Validation",
        "paper_author": "Liang"
      }
    ]
  },
  {
    "category": "Slide-Level & Patient-Level Foundation Models",
    "models": [
      {
        "name": "Prov-GigaPath",
        "year": 2024,
        "data": "1.3B tiles, 171K WSIs",
        "idea": "LongNet for ultra-large context",
        "stains": "H&E + IHC",
        "github": "https://github.com/prov-gigapath/prov-gigapath",
        "hf": "https://huggingface.co/prov-gigapath/prov-gigapath",
        "paper": "https://www.nature.com/articles/s41586-024-07441-w",
        "audit_wsis": "**171,189 H&E/IHC WSIs**",
        "audit_patches": "**1,384,860,229 256\u00d7256 tiles**",
        "audit_wsi_report": "Reports used in V-L experiment",
        "audit_organs": "31 major tissue types",
        "audit_downstream": "**26 tasks: 9 cancer-subtyping + 17 pathomics**",
        "audit_cohorts": "Providence network: **28 cancer centers**, >30K patients",
        "audit_notes": "Private real-world clinical corpus; DINOv2 tile encoder + LongNet/MAE slide encoder.",
        "paper_title": "A whole-slide foundation model for digital pathology from real-world data",
        "paper_author": "Xu"
      },
      {
        "name": "CHIEF",
        "year": 2024,
        "data": "60K WSIs, 19 sites",
        "idea": "Weakly supervised slide pattern recognition",
        "stains": "H&E",
        "github": "https://github.com/hms-dbmi/CHIEF",
        "hf": "",
        "paper": "https://www.nature.com/articles/s41586-024-07894-z",
        "audit_wsis": "**60,530 WSIs**",
        "audit_organs": "**19 anatomical sites**",
        "audit_downstream": "Cancer detection, tumor-origin identification, molecular-profile prediction and prognosis",
        "audit_cohorts": "Validation: **32 independent slide sets from 24 hospitals/cohorts**",
        "audit_notes": "44-TB pretraining corpus; external validation includes 19,491 WSIs.",
        "paper_title": "A pathology foundation model for cancer diagnosis and prognosis prediction",
        "paper_author": "Wang"
      },
      {
        "name": "Feather",
        "year": 2025,
        "data": "3,499 WSIs",
        "idea": "Transferable Pretrained MIL Models",
        "stains": "H&E",
        "github": "https://github.com/mahmoodlab/MIL-Lab",
        "hf": "https://huggingface.co/collections/MahmoodLab/feather",
        "paper": "https://arxiv.org/abs/2506.09022",
        "audit_wsis": "3,499 WSIs (PC-43 / PC-108 pancancer source tasks)",
        "audit_organs": "17 organ types (PC-108); downstream: breast, lung, prostate, brain",
        "audit_downstream": "21 tasks: 19 public CPath tasks + PC-43 & PC-108 pancancer",
        "audit_cohorts": "PC-108 cases from Brigham and Women's Hospital (BWH); other sources not stated",
        "audit_notes": "MIL-Lab transferable pretrained MIL models. Source tasks PC-43 (43 cancer types) and PC-108 (108 OncoTree codes) use 3,499 BWH WSIs.",
        "paper_title": "Do Multiple Instance Learning Models Transfer?",
        "paper_author": "Shao"
      },
      {
        "name": "EXAONE Path 2.0",
        "year": 2025,
        "data": "37K WSIs",
        "idea": "End-to-end hierarchical learning",
        "stains": "H&E (FFPE)",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/pdf/2507.06639",
        "audit_wsis": "37,195 FFPE H&E WSIs",
        "audit_patches": "144,450 image-label pairs (from 37,195 WSIs)",
        "audit_organs": "33 cancer types (subtyping); 12 organ systems (tissue classification)",
        "audit_downstream": "10 biomarker tasks (4 private: LUAD-TMB/EGFR/KRAS, CRC-MSI; 6 public: BRCA-TP53/PIK3CA, RCC-PBRM1/BAP1, COAD-KRAS/TP53)",
        "audit_cohorts": "Private: Korean + 2 US hospitals; Public: CPTAC (BRCA, CCRCC, COAD)",
        "audit_notes": "37,195 FFPE H&E WSIs; end-to-end hierarchical direct slide-level supervision. 33 cancer types, 12 organ systems.",
        "paper_title": "EXAONE Path 2.0: Pathology Foundation Model with End-to-End Supervision",
        "paper_author": "Pyeon"
      },
      {
        "name": "MOOZY",
        "year": 2026,
        "data": "77K WSIs",
        "idea": "Patient-first case-level aggregator",
        "stains": "H&E",
        "github": "https://github.com/AtlasAnalyticsLab/MOOZY",
        "hf": "",
        "paper": "https://arxiv.org/abs/2603.27048",
        "audit_wsis": "**77,134 public slides**",
        "audit_organs": "**23 anatomical sites**",
        "audit_downstream": "**333 tasks: 205 classification + 128 survival**",
        "audit_cohorts": "**56 public datasets**",
        "audit_notes": "Entirely public; patient-first case-level transformer models inter-slide relationships.",
        "paper_title": "MOOZY: A Patient-First Foundation Model for Computational Pathology",
        "paper_author": "Kotp"
      },
      {
        "name": "GigaPath-Flash",
        "year": 2026,
        "data": "Real-world Providence cohort",
        "idea": "Efficient 43M ViT-S+LongNet whole-slide foundation model",
        "stains": "H&E",
        "github": "",
        "hf": "https://huggingface.co/prov-gigapath/prov-gigapath-flash",
        "paper": "https://arxiv.org/abs/2607.18218",
        "audit_organs": "Evaluation: prostate (PANDA), brain (EBRAINS, 30 subtypes), lung (LUAD/LUSC), breast, colon (Prov-TMA)",
        "audit_downstream": "PANDA ISUP grading (6-class), EBRAINS 30-class brain subtyping, + spatial-proteomics prediction",
        "audit_cohorts": "Large real-world clinical data",
        "audit_notes": "22M ViT-S + 21M LongNet (~43M); tile encoder distilled from GigaPath; open-weight Apache-2.0. Providence pretraining size not disclosed.",
        "paper_title": "GigaPath-Flash and GigaTIME-Flash: Efficient Pathology Foundation Models for Whole-Slide and Tumor Microenvironment Analysis",
        "paper_author": "Usuyama"
      }
    ]
  },
  {
    "category": "Vision-Language Foundation Models",
    "models": [
      {
        "name": "PLIP",
        "year": 2023,
        "data": "208K image-text pairs",
        "idea": "Pretrained on medical Twitter",
        "github": "https://github.com/pathologyfoundation/plip",
        "hf": "https://huggingface.co/vinid/plip",
        "paper": "https://doi.org/10.1038/s41591-023-02504-3",
        "audit_patches": "208,414 pathology images",
        "audit_image_text": "**208,414 image\u2013text pairs**",
        "audit_downstream": "4 external zero-shot classification datasets + image/text retrieval",
        "audit_cohorts": "OpenPath / medical Twitter + LAION; institution count not applicable/reported",
        "audit_notes": "Crowdsourced public image-description data.",
        "paper_title": "A visual\u2013language foundation model for pathology image analysis using medical Twitter",
        "paper_author": "Huang"
      },
      {
        "name": "CONCH",
        "year": 2024,
        "data": "1.17M image-text pairs",
        "idea": "CoCa-based task-agnostic pretraining",
        "github": "https://github.com/mahmoodlab/CONCH",
        "hf": "https://huggingface.co/MahmoodLab/CONCH",
        "paper": "https://doi.org/10.1038/s41591-024-02856-4",
        "audit_image_text": "**>1.17M image\u2013caption pairs**",
        "audit_organs": "Diverse histopathology",
        "audit_downstream": "**14 benchmarks** spanning classification, segmentation, captioning, text\u2192image and image\u2192text retrieval, including slide-level few-shot evaluation",
        "audit_cohorts": "Multiple sources",
        "audit_notes": "CoCa-style task-agnostic pathology VLM.",
        "paper_title": "A visual-language foundation model for computational pathology",
        "paper_author": "Lu"
      },
      {
        "name": "PRISM",
        "year": 2024,
        "data": "Virchow tiles + reports",
        "idea": "Generative model via Virchow tiles",
        "stains": "H&E",
        "github": "",
        "hf": "https://huggingface.co/paige-ai/Prism",
        "paper": "https://arxiv.org/abs/2405.10254",
        "audit_wsis": "**587K WSIs**",
        "audit_wsi_report": "195K clinical reports (no explicit one-to-one WSI-report count)",
        "audit_downstream": "Report generation, zero-shot cancer detection/subtyping, biomarker identification, slide classification",
        "audit_cohorts": "**MSKCC**",
        "audit_notes": "Virchow tile embeddings + reports. Do not relabel \u201c195K reports\u201d as \u201c195K WSI-report pairs.\u201d",
        "paper_title": "PRISM: A Multi-Modal Generative Foundation Model for Slide-Level Histopathology",
        "paper_author": "Shaikovski"
      },
      {
        "name": "MUSK",
        "year": 2025,
        "data": "50M images + 1B text tokens",
        "idea": "Unified masked modeling",
        "github": "https://github.com/lilab-stanford/MUSK",
        "hf": "",
        "paper": "https://www.nature.com/articles/s41586-024-08378-w",
        "audit_patches": "**50M pathology images**",
        "audit_image_text": "**1M image\u2013text pairs** in alignment stage",
        "audit_downstream": "**23 patch- and slide-level benchmarks**, including retrieval, VQA, classification and biomarker prediction",
        "audit_cohorts": "**11,577 patients**",
        "audit_notes": "First-stage language corpus also contains **1B pathology-related text tokens**; initial image/text can be unpaired.",
        "paper_title": "A vision\u2013language foundation model for precision oncology",
        "paper_author": "Xiang"
      },
      {
        "name": "TITAN",
        "year": 2025,
        "data": "335K WSIs + reports",
        "idea": "Whole-slide alignment with reports",
        "stains": "H&E 89.7%, IHC 7.9%, special 2.3%, other 0.1%",
        "github": "https://github.com/mahmoodlab/TITAN",
        "hf": "https://huggingface.co/MahmoodLab/TITAN",
        "paper": "https://www.nature.com/articles/s41591-025-03982-3",
        "audit_wsis": "**335,645 WSIs**",
        "audit_image_text": "**423,122 synthetic image/ROI\u2013caption examples**",
        "audit_wsi_report": ">182K pathology reports (slide-report cardinality unspecified)",
        "audit_organs": "**20 organs**",
        "audit_downstream": "6 broad families: linear probing, few-shot classification, zero-shot classification, rare-cancer retrieval, cross-modal retrieval, report generation",
        "audit_cohorts": "Mass General Brigham",
        "audit_notes": "89.7% H&E, 7.9% IHC, 2.3% special stains, 0.1% other; captions generated with PathChat.",
        "paper_title": "A multimodal whole-slide foundation model for pathology",
        "paper_author": "Ding"
      },
      {
        "name": "CPath-Omni",
        "year": 2025,
        "data": "700k image-caption + WSI report",
        "idea": "Unified Patch\u2013Slide Multimodal Model",
        "github": "https://github.com/PathFoundation/CPath-Omni",
        "hf": "",
        "paper": "https://arxiv.org/pdf/2412.12077",
        "audit_wsis": "7,312 WSI-caption examples + 5,850 WSI reports (no single corpus total)",
        "audit_image_text": "700,145 image-caption pairs (PathCap 218,630 + Quilt-1M 388,932 + OpenPath 92,583)",
        "audit_wsi_report": "5,850 cleaned WSI reports + 7,312 WSI-level captioning examples (HistGen)",
        "audit_organs": "8 TCGA subtyping tasks: RCC, NSCLC, BRCA, UCEC, THCA, ESCA, BLCA, TGCT",
        "audit_downstream": "7 tasks across 42 datasets (39 SOTA): patch classification, VQA, captioning, visual referring; WSI classification, VQA, captioning",
        "audit_cohorts": "21 public patch datasets + 9 WSI-level datasets; TCGA primary",
        "audit_notes": "15B-parameter unified patch/WSI model (Qwen2.5-14B backbone). CPath-PatchCaption corpus: 700,145 image-caption pairs.",
        "paper_title": "CPath-Omni: A Unified Multimodal Foundation Model for Patch and Whole Slide Image Analysis in Computational Pathology",
        "paper_author": "Sun"
      },
      {
        "name": "KEEP",
        "year": 2026,
        "data": "143K knowledge-grouped pairs",
        "idea": "Disease knowledge graph integration",
        "github": "https://github.com/MAGIC-AI4Med/KEEP",
        "hf": "https://huggingface.co/Astaxanthin/KEEP",
        "paper": "https://arxiv.org/abs/2412.13126",
        "audit_wsis": "Pretrained on image-text pairs, not WSIs",
        "audit_image_text": "143K knowledge-grouped semantic groups from millions of OpenPath + Quilt-1M image-text pairs",
        "audit_organs": "Downstream spans ~10 tissue types; disease knowledge graph covers 11,454 diseases",
        "audit_downstream": "18 benchmarks (>14,000 WSIs) + 14 tile datasets over 7 tissue types: segmentation, detection, subtyping (incl. 30 rare brain subtypes), cross-modal retrieval",
        "audit_cohorts": "Pretraining from OpenPath + Quilt-1M; institution count not stated",
        "audit_notes": "Disease knowledge graph: 11,454 diseases, 139,143 attributes; 143K knowledge-grouped image-text pairs. Published in Cancer Cell (2026).",
        "paper_title": "Knowledge-enhanced Pretraining for Vision-language Pathology Foundation Model on Cancer Diagnosis",
        "paper_author": "Zhou"
      },
      {
        "name": "PRISM2",
        "year": 2026,
        "data": "2.3M WSIs",
        "idea": "Clinical Dialogue Multimodal Pretraining",
        "stains": "H&E",
        "github": "",
        "hf": "https://huggingface.co/paige-ai/Prism2",
        "paper": "https://arxiv.org/abs/2506.13063",
        "audit_wsis": "**2.3M WSIs**",
        "audit_wsi_report": "~700K specimens / 2.3M WSIs have diagnostic reports (no explicit pair total isolated)",
        "audit_downstream": "Diagnostic/biomarker/report-QA and survival-oriented evaluations",
        "audit_cohorts": "Nearly 700K specimens",
        "audit_notes": "One report-bearing specimen can have several slides, hence 2.3M \u2260 2.3M WSI-report pairs.",
        "paper_title": "PRISM2: Unlocking Multi-Modal General Pathology AI with Clinical Dialogue",
        "paper_author": "Vorontsov"
      }
    ]
  },
  {
    "category": "Multimodal & Molecular Foundation Models",
    "models": [
      {
        "name": "Tangle",
        "year": 2024,
        "data": "8.6K paired (slide + RNA-seq)",
        "idea": "Transcriptomics-aligned slide representation",
        "stains": "H&E",
        "github": "https://github.com/mahmoodlab/Tangle",
        "hf": "",
        "paper": "https://arxiv.org/abs/2405.11618",
        "audit_wsis": "Slide encoder trained on 8,629 paired slides; tile encoder (iBOT-Tox) pretrained on 47,227 liver/kidney WSIs",
        "audit_image_omics": "8,629 paired slide + RNA-seq samples (TG-GATEs liver 6,597; TCGA-BRCA 1,041; TCGA-NSCLC 1,031)",
        "audit_organs": "Liver (rat), breast, lung (human)",
        "audit_downstream": "3 tasks: few-shot linear probing, prototype classification, slide retrieval; 3 test datasets (liver, breast, lung)",
        "audit_cohorts": "TG-GATEs (rat) + TCGA-BRCA + TCGA-NSCLC; plus in-house breast/lung cohorts",
        "audit_notes": "Confirmed 8,629 paired slide+RNA-seq (TG-GATEs 6,597, TCGA-BRCA 1,041, TCGA-NSCLC 1,031).",
        "paper_title": "Transcriptomics-guided Slide Representation Learning in Computational Pathology",
        "paper_author": "Jaume"
      },
      {
        "name": "Madeleine",
        "year": 2025,
        "data": "4,211 WSIs (Paired Multi-Stain)",
        "idea": "Multistain Cross-Stain Slide Pretraining",
        "stains": "Multi-stain: breast H&E + ER/PR/HER2/KI67; kidney H&E + PAS/Jones/Trichrome",
        "github": "https://github.com/mahmoodlab/MADELEINE",
        "hf": "https://huggingface.co/MahmoodLab/madeleine",
        "paper": "https://arxiv.org/pdf/2408.02859",
        "audit_wsis": "4,211 breast WSIs (1,153 cases, Acrobat) + BWH kidney 12,070 WSIs across 4 stains (1,069 cases; ~80% for pretraining)",
        "audit_image_omics": "Paired multi-stain (breast: H&E + ER/PR/HER2/KI67; kidney: H&E + PAS/Jones/Trichrome)",
        "audit_organs": "Breast cancer; kidney transplant",
        "audit_downstream": "21 tasks (7,299 WSIs): morphological & molecular subtyping, survival, IHC quantification, transplant-rejection screening",
        "audit_cohorts": "Pretraining: Acrobat (breast) + BWH (kidney); eval: TCGA-BRCA, BCNB, AIDPATH, BWH/MGH breast, BWH kidney",
        "audit_notes": "Confirmed 4,211 breast WSIs (1,153 cases, Acrobat) plus BWH multi-stain kidney corpus. Cross-stain slide pretraining.",
        "paper_title": "Multistain Pretraining for Slide Representation Learning in Pathology",
        "paper_author": "Jaume"
      },
      {
        "name": "Threads",
        "year": 2025,
        "data": "47K paired (H&E + multi-omics)",
        "idea": "Multi-omics driven representation",
        "stains": "H&E",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/html/2501.16652v1",
        "audit_patches": "125,148,770 patches (512x512 @ 20x)",
        "audit_image_omics": "47,171 H&E sections paired with genomic + transcriptomic profiles (BWH 20,556; TCGA 10,209; GTEx 9,507; MGH 6,899)",
        "audit_organs": "39 major organs",
        "audit_downstream": "54 tasks: 8 subtyping/grading, 21 mutation, 12 IHC status, 13 treatment response/survival",
        "audit_cohorts": "23 cohorts from 17 sources; downstream 28,856 WSIs (PANDA 9,555; IMP 5,333; EBRAINS 2,319; CPTAC 2,115)",
        "audit_notes": "47,171 H&E sections + omics; 125M patches (512x512 @ 20x); 39 organs; 54 downstream tasks. Primary source says tissue sections, not necessarily distinct WSIs.",
        "paper_title": "Molecular-driven Foundation Model for Oncologic Pathology",
        "paper_author": "Vaidya"
      },
      {
        "name": "mSTAR",
        "year": 2025,
        "data": "26K paired triplets",
        "idea": "Slide, report, and RNA-seq integration",
        "stains": "H&E",
        "github": "https://github.com/Innse/mSTAR",
        "hf": "https://huggingface.co/Wangyh/mSTAR",
        "paper": "https://www.nature.com/articles/s41467-025-66220-x",
        "audit_patches": "**>116M patch images**",
        "audit_image_omics": "**26,169 aggregate slide-level modality pairs** spanning H&E WSIs, reports and RNA-seq; 10,275 patients",
        "audit_organs": "**32 cancer types**",
        "audit_downstream": "**43 subtasks across 7 task types**",
        "audit_notes": "Crucially, the 26,169 aggregate multimodal pairs cannot be safely split into invented WSI-report and WSI-RNA counts.",
        "paper_title": "A multimodal knowledge-enhanced whole-slide pathology foundation model",
        "paper_author": "Xu"
      },
      {
        "name": "KRONOS",
        "year": 2025,
        "data": "47M patches",
        "idea": "Foundation model built for spatial proteomics via segmentation-free patch-level processing",
        "stains": "Multiplexed immunofluorescence (175 protein markers)",
        "github": "https://github.com/mahmoodlab/KRONOS",
        "hf": "https://huggingface.co/MahmoodLab/KRONOS",
        "paper": "https://arxiv.org/abs/2506.03373",
        "audit_wsis": "Spatial-proteomics image corpus (not conventional WSI pretraining)",
        "audit_patches": "**>47M spatial-proteomics image patches**",
        "audit_image_omics": "47M+ patches cover **175 protein markers**",
        "audit_organs": "**16 tissue types**",
        "audit_downstream": "Cell phenotyping, region classification, patient stratification, treatment-response prediction, retrieval/reverse search",
        "audit_cohorts": "**11 independent evaluation cohorts; 8 fluorescence imaging platforms**",
        "audit_notes": "Segmentation-free, multi-channel spatial-proteomics FM.",
        "paper_title": "A Foundation Model for Spatial Proteomics",
        "paper_author": "Shaban"
      },
      {
        "name": "EXAONE Path 2.5",
        "year": 2025,
        "data": "37K WSIs",
        "idea": "End-to-end hierarchical learning with direct slide-level supervision",
        "stains": "H&E",
        "github": "",
        "hf": "https://huggingface.co/LGAI-EXAONE/EXAONE-Path-2.5",
        "paper": "https://arxiv.org/abs/2512.14019",
        "audit_image_omics": "Histology aligned with **genomic, epigenetic and transcriptomic** modalities",
        "audit_downstream": "Patho-Bench **80 tasks** + internal real-world clinical benchmark",
        "audit_cohorts": "Two evaluation settings",
        "audit_notes": "All-pairwise SigLIP-style multimodal alignment; pretraining sample counts not explicit in accessible abstract.",
        "paper_title": "EXAONE Path 2.5: Pathology Foundation Model with Multi-Omics Alignment",
        "paper_author": "Yun"
      },
      {
        "name": "CARE",
        "year": 2026,
        "data": "34K WSIs",
        "idea": "Molecular-Guided Adaptive Region Modeling",
        "stains": "H&E",
        "github": "https://github.com/zdipath/CARE",
        "hf": "https://huggingface.co/Zipper-1/CARE",
        "paper": "https://arxiv.org/abs/2602.21637",
        "audit_wsis": "34,277 WSIs (11,463 TCGA H&E FFPE + 22,814 GTEx normal)",
        "audit_patches": "285,710 sub-WSIs (DBSCAN clusters, <=360 patches each)",
        "audit_image_omics": "13,289 WSI-RNA pairs + 8,225 WSI-protein pairs",
        "audit_organs": "Pan-cancer (TCGA + GTEx); eval spans CPTAC (GBM/BRCA/CCRCC/COAD/HNSCC/LUAD/PDA), EBRAINS, colorectal, breast, lung",
        "audit_downstream": "33 tasks across 9 datasets (CPTAC, EBRAINS, MUT-HET-RCC, IMP, BCNB, DHMC-LUAD, DHMC-RCC, SR386, Local-LUNG)",
        "audit_cohorts": "Pretraining: TCGA + GTEx; eval: CPTAC + 7 additional public/institutional cohorts",
        "audit_notes": "Confirmed 34,277 pretraining WSIs (TCGA 11,463 + GTEx 22,814). Molecular-guided adaptive region modeling; 13,289 WSI-RNA + 8,225 WSI-protein pairs.",
        "paper_title": "CARE: A Molecular-Guided Foundation Model with Adaptive Region Modeling for Whole Slide Image Analysis",
        "paper_author": "Zhang"
      },
      {
        "name": "KRONOS2",
        "year": 2026,
        "data": "SPM56M patches; 268 markers",
        "idea": "Marker-aware DINOv2 successor to KRONOS (268 markers)",
        "stains": "Multiplexed immunofluorescence (268 protein markers)",
        "github": "",
        "hf": "https://huggingface.co/MahmoodLab/KRONOS2",
        "paper": "https://arxiv.org/abs/2506.03373",
        "audit_wsis": "Spatial-proteomics image corpus",
        "audit_patches": "SPM56M pretraining set (name implies ~56M spatial-proteomics patches; exact count not on card)",
        "audit_image_omics": "Pretraining marker vocabulary: 268 protein markers (vs 175 in KRONOS)",
        "audit_notes": "Marker-aware DINOv2 ViT-B/16, next-gen successor to KRONOS. No distinct KRONOS2 paper yet - shares the KRONOS arXiv (Shaban et al., 2025).",
        "paper_title": "A foundation model for spatial proteomics",
        "paper_author": "Shaban"
      },
      {
        "name": "GigaTIME-Flash",
        "year": 2026,
        "data": "Real-world Providence cohort",
        "idea": "Efficient spatial proteomics prediction from H&E",
        "stains": "H&E (predicts multiplex-IF markers)",
        "github": "",
        "hf": "https://huggingface.co/prov-gigatime/gigatime-flash",
        "paper": "https://arxiv.org/abs/2607.18218",
        "audit_image_omics": "Spatial-proteomics prediction supervision",
        "audit_organs": "Evaluation: prostate, brain, lung (LUAD/LUSC), breast, colon (Prov-TMA)",
        "audit_downstream": "Tumor immune microenvironment / spatial-proteomics prediction (windowed Pearson on mIF markers)",
        "audit_cohorts": "Large real-world clinical data",
        "audit_notes": "Uses the compact GigaPath-Flash visual backbone. Providence pretraining size not disclosed.",
        "paper_title": "GigaPath-Flash and GigaTIME-Flash: Efficient Pathology Foundation Models for Whole-Slide and Tumor Microenvironment Analysis",
        "paper_author": "Usuyama"
      }
    ]
  },
  {
    "category": "Foundation Model Adaptation & Distillation",
    "models": [
      {
        "name": "H0-mini",
        "type": "Single-FM Distillation",
        "year": 2025,
        "data": "43 million tiles, 6,093 WSIs",
        "idea": "Lightweight foundation model distilled from H-optimus-0 with DINOv2",
        "stains": "H&E",
        "github": "",
        "hf": "https://huggingface.co/bioptimus/H0-mini",
        "paper": "https://arxiv.org/abs/2501.16239",
        "paper_title": "Distilling foundation models for robust and efficient models in digital pathology",
        "paper_author": "Filiot",
        "audit_wsis": "6,093 WSIs",
        "audit_patches": "43 million tiles",
        "audit_organs": "PanCancer",
        "audit_downstream": "Slide-level classification (e.g., ABMIL)",
        "audit_cohorts": "TCGA",
        "audit_notes": "Distilled from H-optimus-0 (ViT-g/14) using DINOv2 self-supervised distillation method on PanCancer40M."
      },
      {
        "name": "SEAL",
        "year": 2026,
        "data": "---",
        "idea": "---",
        "stains": "H&E (+ spatial transcriptomics)",
        "github": "https://github.com/mahmoodlab/SEAL/",
        "hf": "https://huggingface.co/MahmoodLab/SEAL",
        "paper": "https://arxiv.org/abs/2602.14177",
        "audit_wsis": "Parameter-efficient vision-omics adaptation (no new WSI corpus)",
        "audit_image_omics": "**>700K paired spatial-transcriptomics gene-expression spot\u2013tissue-region examples**",
        "audit_organs": "**14 organs**",
        "audit_downstream": "**53 tasks = 38 slide-level + 15 patch-level**; molecular status, pathways, treatment response, gene-expression prediction, gene\u2192image retrieval",
        "audit_notes": "ST-guided fine-tuning of existing PFMs rather than a wholly new from-scratch visual encoder.",
        "paper_title": "Towards Spatial Transcriptomics-driven Pathology Foundation Models",
        "paper_author": "Hemker",
        "type": "Vision\u2013omics adaptation"
      },
      {
        "name": "Phaet",
        "year": 2026,
        "data": "---",
        "idea": "Robustness-tuned Phikon-v2",
        "stains": "H&E",
        "github": "",
        "hf": "https://huggingface.co/wearewaiv/phaet",
        "paper": "https://arxiv.org/abs/2607.22861",
        "audit_wsis": "Fine-tuned from Phikon-v2 (no new from-scratch corpus)",
        "audit_downstream": "PathoROB; HEST (9 cancer/ST tasks); THUNDER (6 task types over 16 datasets); 63 Patho-Bench tasks used in this study",
        "audit_cohorts": "PathoROB includes 34 medical centers",
        "audit_notes": "Robustness-tuned Phikon-v2, not an independently pretrained FM.",
        "paper_title": "Robustifying pathology foundation models via fine-tuning",
        "paper_author": "Filiot",
        "type": "Robustness adaptation"
      },
      {
        "name": "Mascaret",
        "year": 2026,
        "data": "---",
        "idea": "Robustness-tuned Midnight-12k",
        "stains": "H&E",
        "github": "",
        "hf": "https://huggingface.co/wearewaiv/mascaret",
        "paper": "https://arxiv.org/abs/2607.22861",
        "audit_wsis": "Fine-tuned from Midnight-12k (no new from-scratch corpus)",
        "audit_downstream": "Same robustness suites as Phaet: PathoROB, HEST, THUNDER, Patho-Bench subset",
        "audit_cohorts": "PathoROB includes 34 medical centers",
        "audit_notes": "Robustness-tuned Midnight-12k.",
        "paper_title": "Robustifying pathology foundation models via fine-tuning",
        "paper_author": "Filiot",
        "type": "Robustness adaptation"
      }
    ]
  },
  {
    "category": "Multi-FM Integration & Distillation",
    "models": [
      {
        "name": "GPFM",
        "year": 2025,
        "data": "190M tiles, 96K WSIs",
        "idea": "Multi-teacher distillation",
        "stains": "H&E",
        "github": "https://github.com/birkhoffkiki/GPFM/",
        "hf": "",
        "paper": "https://arxiv.org/abs/2407.18449",
        "audit_wsis": "**~86K public H&E WSIs**",
        "audit_patches": "**190M images**",
        "audit_organs": "**34 major tissue types**",
        "audit_downstream": "**39 specific tasks across 6 clinical task types**",
        "audit_cohorts": "Public datasets",
        "audit_notes": "Expert + self knowledge distillation. **Primary source says ~86K, not 96K WSIs.**",
        "paper_title": "Towards A Generalizable Pathology Foundation Model via Unified Knowledge Distillation",
        "paper_author": "Ma"
      },
      {
        "name": "COBRA",
        "year": 2025,
        "data": "3048 WSIs",
        "idea": "Multi-FM representation integration",
        "stains": "H&E",
        "github": "https://github.com/KatherLab/COBRA",
        "hf": "https://huggingface.co/KatherLab/COBRA",
        "paper": "https://arxiv.org/abs/2411.13623",
        "audit_wsis": "3,048 WSIs / 2,848 patients (TCGA: BRCA 1,112, CRC 566, LUAD 524, LUSC 496, STAD 350)",
        "audit_patches": "Uses tile embeddings from several PFMs",
        "audit_organs": "5 cancer types: BRCA, CRC, LUAD, LUSC, STAD",
        "audit_downstream": "13 biomarker-prediction tasks; TCGA (train) + CPTAC external validation",
        "audit_cohorts": "TCGA 3,048 WSIs (2,848 patients); CPTAC 1,604 WSIs (444 patients)",
        "audit_notes": "Confirmed 3,048 WSIs / 2,848 patients (TCGA). Integrates 4 FMs: CTransPath, UNI, Virchow2, H-optimus-0.",
        "paper_title": "Unsupervised Foundation Model-Agnostic Slide-Level Representation Learning",
        "paper_author": "Lenz"
      },
      {
        "name": "ELF",
        "year": 2025,
        "data": "53K WSIs (20 anatomical sites)",
        "idea": "Ensemble learning",
        "stains": "H&E",
        "github": "https://github.com/lilab-stanford/ELF",
        "hf": "",
        "paper": "https://arxiv.org/abs/2508.16085",
        "audit_wsis": "53,699 WSIs across 11 public datasets, 20 anatomical sites",
        "audit_patches": "Integrates outputs from 5 PFMs",
        "audit_organs": "20 anatomical sites (e.g., prostate 11,208; skin 9,610; colorectal 7,844; heart 3,824; breast 2,982; brain 2,764)",
        "audit_downstream": "115 tasks: 3 disease-classification datasets (BCCC, BRACS, EBRAINS), 74 TCGA biomarker-indication combos, 21 therapy-response cohorts (9 cancers), 12 immunotherapy cohorts (8 cancers)",
        "audit_cohorts": "11 public pretraining datasets (ACROBAT, BCNB, COBRA, DHMC, GTEx, IMP-CRS, IPD-Brain, NMI-Bladder, PAIP, PANDA, TCGA); eval up to 11,530 patients",
        "audit_notes": "Confirmed 53,699 pretraining WSIs, 20 anatomical sites, 11 public datasets. Ensembles 5 FMs: GigaPath, CONCH v1.5, Virchow2, H-optimus-0, UNI.",
        "paper_title": "Ensemble learning of foundation models for precision oncology",
        "paper_author": "Luo"
      },
      {
        "name": "Shazam",
        "year": 2026,
        "data": "Fuses 5 models (UNI 2, Virchow2, H-optimus-1, Prov-Gigapath, Phikon-v2)",
        "idea": "Adaptive integration/distillation",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2503.00736",
        "audit_wsis": "No standalone fixed pretraining corpus",
        "audit_patches": "Online integration of pretrained FM representations",
        "audit_downstream": "**4 task families:** spatial-transcriptomics prediction, survival prognosis, tile classification, VQA",
        "audit_cohorts": "Dataset-dependent",
        "audit_notes": "Adaptive online expert weighting/distillation; categorically different from offline corpus distillation.",
        "paper_title": "Unifying Multiple Foundation Models for Advanced Computational Pathology",
        "paper_author": "Lei"
      },
      {
        "name": "ALICE",
        "year": 2026,
        "data": "24.9M tiles + 155K high-res images",
        "idea": "Agglomerative distillation",
        "stains": "H&E",
        "github": "https://github.com/WonderLandxD/ALICE",
        "hf": "",
        "paper": "https://arxiv.org/pdf/2607.09526",
        "audit_wsis": "~12K TCGA WSIs (low-res) + 9,662 FFPE WSIs (high-res ROIs) + HISTAI slides",
        "audit_patches": "**24,985,184 tile-level pathology images + 155,604 high-resolution images**",
        "audit_organs": "32 TCGA cancer types; HISTAI (breast, colorectal, skin, thorax); + CNS, H&N, ovarian, renal, lung, prostate, gastric, esophageal",
        "audit_downstream": "96 tasks / 21 scenarios: ROI analysis, vision-language, whole-slide clinical assessment",
        "audit_cohorts": "48 datasets (TCGA, HISTAI, BRACS, BreakHis, CRC-100K, CAMELYON+, CPTAC, EBRAINS, PANDA, ...)",
        "audit_notes": "Agglomerative distillation from 8 teachers: UNI-2, Virchow-2, H-Opt-1 (vision); CONCH, MUSK, KEEP (VLM); TITAN, CARE (slide).",
        "paper_title": "ALICE: Learning a General-Purpose Pathology Foundation Model from Vision, Vision-Language, and Slide-Level Experts",
        "paper_author": "Li"
      },
      {
        "name": "ASTRA",
        "year": 2026,
        "data": "10.3K WSIs (CHTN cohort)",
        "idea": "MoE fusion/alignment",
        "stains": "H&E",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2604.22846",
        "audit_wsis": "Developed on 10,359 CHTN WSIs",
        "audit_patches": "integrates existing FM representations",
        "audit_image_text": "Structured pathology prompts used",
        "audit_organs": "**16 tumor types**",
        "audit_downstream": "4 main task settings: 4-category classification, 3-class solid-tumor typing, 16-class cancer typing, text-guided tumor localization",
        "audit_cohorts": "CHTN development 10,359 WSIs + external TCGA 1,686 WSIs",
        "audit_notes": "\u201cDeveloped on\u201d is preserved rather than relabeled as \u201cpretrained on.\u201d",
        "paper_title": "Unified Multi-Foundation-Model Slide Representation for Pan-Cancer Recognition and Text-Guided Tumor Localization",
        "paper_author": "Wang"
      }
    ]
  },
  {
    "category": "Segmentation & Interactive Foundation Models",
    "models": [
      {
        "name": "VISTA-PATH",
        "year": 2026,
        "data": "1.65M triplets (Image + Mask + Text)",
        "idea": "Interactive Class-Aware Segmentation",
        "stains": "H&E",
        "github": "https://github.com/zhihuanglab/VISTA-PATH",
        "hf": "",
        "paper": "https://arxiv.org/abs/2601.16451",
        "audit_patches": "**>1.6M image\u2013mask\u2013text triplets**",
        "audit_image_text": "**>1.6M triplets contain a text component**",
        "audit_organs": "**9 organs; 93 tissue classes**",
        "audit_downstream": "Held-out/external semantic segmentation plus TME quantitative/survival analyses",
        "audit_cohorts": "Multiple external/held-out datasets",
        "audit_notes": "Triplet-based corpus rather than WSI-count-based pretraining.",
        "paper_title": "VISTA-PATH: An interactive foundation model for pathology image segmentation and quantitative analysis in computational pathology",
        "paper_author": "Liang"
      }
    ]
  },
  {
    "category": "Generative Foundation Models",
    "models": [
      {
        "name": "MuPD",
        "year": 2026,
        "data": "100M patches",
        "idea": "Multimodal Pathology Diffusion Model",
        "stains": "H&E",
        "github": "https://github.com/lilab-stanford/MUPAD",
        "hf": "https://huggingface.co/collections/xiangjx/mupad-multimodal-pathology-diffusion-model",
        "paper": "https://arxiv.org/abs/2604.03635",
        "audit_patches": "**100M histology patches**",
        "audit_image_text": "**1.6M text\u2013histology pairs**",
        "audit_image_omics": "**10.8M RNA\u2013histology pairs**",
        "audit_organs": "**34 human organs**",
        "audit_downstream": "Text-conditioned generation, image-to-image generation, RNA-conditioned generation, virtual staining, synthetic-data augmentation; no single explicit scalar total",
        "audit_cohorts": "TCGA, GTEx, PAIP, PLCO (H&E); PathGen-1.6M (image-text); TCGA bulk RNA-seq (RNA-image). MOSAIC used for ST evaluation only.",
        "audit_notes": "Multimodal pathology diffusion transformer; synthetic images are also assessed as augmentation data.",
        "paper_title": "A Generative Foundation Model for Multimodal Histopathology",
        "paper_author": "Xiang"
      }
    ]
  },
  {
    "category": "Foundation Model Benchmarking",
    "models": [
      {
        "name": "EVA",
        "year": 2024,
        "data": "Slide & Patch",
        "idea": "Standardized framework for systematic evaluation and comparison of PFMs",
        "github": "https://github.com/kaiko-ai/eva",
        "hf": "",
        "paper": "https://openreview.net/forum?id=FNBQOPj18N",
        "audit_downstream": "Standardized patch-/slide-level FM evaluation framework",
        "audit_notes": "Benchmark rather than pretrained model.",
        "paper_title": "eva: Evaluation framework for pathology foundation models",
        "paper_author": "kaiko.ai"
      },
      {
        "name": "Patho-Bench",
        "year": 2025,
        "data": "Slide",
        "idea": "Open-source benchmarking toolkit with standardized datasets and reproducible evaluation pipelines",
        "github": "https://github.com/mahmoodlab/Patho-Bench",
        "hf": "",
        "paper": "https://arxiv.org/pdf/2502.06750",
        "audit_organs": "Multi-organ oncology",
        "audit_downstream": "**95 tasks across 7 categories:** morphological subtyping, TME characterization, tumor grading, molecular subtyping, mutation prediction, treatment response, survival",
        "audit_cohorts": "Multiple public datasets",
        "audit_notes": "Open-source standardized slide-level benchmarking framework; the 95-task scope is also explicitly referenced by the Phaet/Mascaret evaluation.",
        "paper_title": "Accelerating Data Processing and Benchmarking of AI Models for Pathology",
        "paper_author": "Zhang"
      },
      {
        "name": "QuIIL-PathBench",
        "year": 2025,
        "data": "Patch",
        "idea": "Systematically benchmarks PFMs by evaluating patch-level representations",
        "github": "https://github.com/QuIIL/BenchmarkingPathologyFoundationModels",
        "hf": "",
        "paper": "https://arxiv.org/abs/2410.16038",
        "audit_downstream": "Patch-level PFM benchmarking",
        "audit_notes": "Benchmark, not a pretraining corpus.",
        "paper_title": "Benchmarking Pathology Foundation Models: Adaptation Strategies and Scenarios",
        "paper_author": "Lee"
      },
      {
        "name": "Clinical Benchmark",
        "year": 2025,
        "data": "Slide",
        "idea": "Clinical benchmark with MSHS and MSKCC datasets covering disease detection and biomarker prediction",
        "github": "https://github.com/sinai-computational-pathology/SSL_tile_benchmarks#automated-external-benchmarking",
        "hf": "",
        "paper": "https://www.nature.com/articles/s41467-025-58796-1.pdf",
        "audit_patches": "**9,528 evaluation H&E WSIs** \u2014 not pretraining patches",
        "audit_organs": "**4 cancer types**",
        "audit_downstream": "**31 weakly supervised tasks: 5 morphology + 19 biomarker + 7 prognostication**",
        "audit_cohorts": "**13 cohorts; 6,818 patients**; includes TCGA/CPTAC and external cohorts such as DACHS, Bern, Kiel and IEO",
        "audit_notes": "Evaluates **19 FMs + 14 ensembles**. Evaluation slides must not be mistaken for pretraining data.",
        "paper_title": "A clinical benchmark of public self-supervised pathology foundation models",
        "paper_author": "Campanella"
      },
      {
        "name": "PathBench",
        "year": 2025,
        "data": "Slide & Patch",
        "idea": "Leakage-free multi-center clinical benchmark spanning multiple tasks, with a live public leaderboard",
        "github": "https://github.com/birkhoffkiki/PathBench",
        "hf": "",
        "website": "https://birkhoffkiki.github.io/PathBench/",
        "paper": "https://arxiv.org/abs/2505.20202",
        "audit_downstream": "Leakage-free slide/patch multi-center clinical benchmark",
        "audit_cohorts": "Multi-center",
        "audit_notes": "Public leaderboard; benchmark rather than model.",
        "paper_title": "PathBench: A comprehensive comparison benchmark for pathology foundation models towards precision oncology",
        "paper_author": "Ma"
      },
      {
        "name": "Stanford PathBench",
        "year": 2026,
        "data": "Slide & Patch",
        "idea": "Comprehensive benchmark of 32 PFMs across 41 tasks with a public leaderboard",
        "github": "",
        "hf": "",
        "paper": "https://www.nature.com/articles/s41467-026-76004-6",
        "audit_patches": "Evaluation uses slide- and patch-level TCGA/CPTAC/external data",
        "audit_organs": "Multiple tissues",
        "audit_downstream": "**32 foundation models** evaluated across slide- and patch-level task categories",
        "audit_cohorts": "TCGA, CPTAC and external/OOD datasets",
        "audit_notes": "Published July 24, 2026; decision-level ensembling also evaluated. The seed-list \u201c41 tasks\u201d figure is not asserted here because I did not independently recover it from the accessible primary source.",
        "paper_title": "A benchmark study of vision and pathology foundation models for computational pathology",
        "paper_author": "Bareja"
      }
    ]
  },
  {
    "category": "Survey and Perspectives",
    "models": [
      {
        "name": "Xiong et al.",
        "year": 2025,
        "data": "",
        "idea": "Comprehensive survey of progress and future directions in pathology foundation models",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2504.04045",
        "paper_title": "A Survey of Pathology Foundation Model: Progress and Future Directions",
        "paper_author": "Xiong",
        "audit_notes": "Survey paper"
      },
      {
        "name": "Chanda et al.",
        "year": 2024,
        "data": "",
        "idea": "Survey on Foundation and Vision-Language Models",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2408.14496",
        "paper_title": "A New Era in Computational Pathology: A Survey on Foundation and Vision-Language Models",
        "paper_author": "Chanda",
        "audit_notes": "Survey paper"
      },
      {
        "name": "Li et al.",
        "year": 2025,
        "data": "",
        "idea": "Survey covering datasets, adaptation strategies, and evaluation tasks",
        "github": "",
        "hf": "",
        "paper": "https://link.springer.com/article/10.1007/s10115-026-02806-1",
        "paper_title": "A survey on computational pathology foundation models: datasets, adaptation strategies, and evaluation tasks",
        "paper_author": "Li",
        "audit_notes": "Survey paper"
      },
      {
        "name": "Lin et al.",
        "year": 2025,
        "data": "",
        "idea": "Quantitative perspective on ethical risks in pathology foundation models",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2502.16889",
        "paper_title": "Revealing Ethical Risks in Pathology Foundation Models: A Quantitative Perspective",
        "paper_author": "Lin",
        "audit_notes": "Perspective paper on ethical risks",
        "tag": "perspective",
        "tag_color": "purple"
      },
      {
        "name": "Bilal et al.",
        "year": 2025,
        "data": "",
        "idea": "Review of challenges, opportunities, and impact of Foundation Models in CPath",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2502.08333",
        "paper_title": "Foundation Models in Computational Pathology: A Review of Challenges, Opportunities, and Impact",
        "paper_author": "Bilal",
        "audit_notes": "Survey paper"
      },
      {
        "name": "Tizhoosh",
        "year": 2026,
        "data": "",
        "idea": "Perspective on rethinking foundation models in pathology",
        "github": "",
        "hf": "",
        "paper": "https://www.nature.com/articles/s41551-026-01696-6",
        "paper_title": "Rethinking foundation models in pathology",
        "paper_author": "Tizhoosh",
        "audit_notes": "Perspective paper",
        "tag": "perspective",
        "tag_color": "purple"
      }
    ]
  },
  {
    "category": "Interpretability and Analysis",
    "models": [
      {
        "name": "Mishra et al.",
        "year": 2025,
        "data": "",
        "idea": "Comparing Computational Pathology Foundation Models using Representational Similarity Analysis",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2509.15482",
        "paper_title": "Comparing Computational Pathology Foundation Models using Representational Similarity Analysis",
        "paper_author": "Mishra",
      },
      {
        "name": "Le et al.",
        "year": 2024,
        "data": "",
        "idea": "Interpretability analysis on a pathology foundation model reveals biologically relevant embeddings across modalities",
        "github": "",
        "hf": "",
        "paper": "https://arxiv.org/abs/2407.10785v1",
        "paper_title": "Interpretability analysis on a pathology foundation model reveals biologically relevant embeddings across modalities",
        "paper_author": "Le",
      }
    ]
  }
];

// Node.js export (browser ignores this — `module` is undefined in the browser).
if (typeof module !== 'undefined' && module.exports) {
  module.exports = modelData;
}
